/* "What changed" module content (namespace: changes).
 * Every amount, date, rate and count is passed in as a parameter formatted
 * with App.fmt from the issued record; nothing numeric is written here.
 * [[termId|text]] markers become glossary triggers via App.ui.rich().
 * French drafts are implementation input pending qualified fr-CA review. */
App.i18n.register('changes', {
  'en-CA': {
    overline: 'What changed',
    title: 'What changes in your repayments',
    intro: 'Your [[principal|principal]] payments for {months} are postponed. Compare each term before and after the change, see what stays the same, and check why lower payments for a few months do not mean you owe less.',
    glance: {
      title: 'At a glance',
      temporary: { label: 'Temporary', text: 'No principal payments in {months}. You still pay {interest} of interest each month.' },
      tradeoff: { label: 'Trade-off', text: '{extra} more interest over the remaining schedule. Your final payment moves to {date}.' },
      owing: { label: 'Still owing', text: 'The {deferred} of postponed principal remains owing. It is repaid later in the schedule.' },
    },
    groups: {
      changed: { title: 'Terms that change', intro: 'Each card compares a term before and after the change.' },
      owing: { title: 'What it means for what you owe', intro: 'Lower payments for {period} are temporary cash-flow relief. They do not reduce your debt.' },
      same: { title: 'What stays the same', intro: 'These terms are not affected by the postponement.' },
    },
    schedule: { original: 'Original schedule', revised: 'Revised schedule' },
    badges: { notReduced: 'Debt not reduced' },
    cards: {
      principal: {
        kicker: 'Principal payments',
        title: 'Postponed for {period}, then resumed',
        before: '{amount} per month',
        beforeSub: 'plus interest',
        after: '{zero} for {months}',
        afterSub: 'then {amount} per month from {date}',
        explain: 'The postponed principal is not cancelled. It remains owing and is repaid later in the schedule.',
      },
      interest: {
        kicker: 'Interest',
        title: 'Still paid monthly, and higher in total',
        monthly: 'Monthly interest, {from} to {to}',
        afterNote: 'Same amount each month, still paid monthly',
        total: 'Total interest over the remaining schedule',
        explain: 'Principal is not reduced during the postponement, so interest stays at {interest} a month and the remaining schedule costs {extra} more in interest.',
        costLink: 'Compare the total cost',
      },
      'next-payment': {
        kicker: 'Next payment',
        title: '{amount} on {date}',
        on: 'on {date}',
        explain: 'This payment covers interest only. Principal payments resume on {date}, when the payment becomes {amount}.',
      },
      maturity: {
        kicker: 'Final payment date',
        title: 'Moves {period} later',
        payments: '{count} monthly payments',
        shift: '{period} later',
        explain: 'Principal repayment restarts later, so the schedule ends later: it now has {count} payments instead of {original}.',
        scheduleLink: 'See the full schedule',
      },
      fees: {
        kicker: 'Change fee',
        title: 'No fee for this change',
        before: 'No change fee',
        beforeSub: 'before this notice',
        sub: 'fee for this change, in this fictional scenario',
        explain: 'No fee applies in this example. The change still has a cost: the additional interest shown on the Interest card.',
      },
      rate: {
        kicker: 'Interest rate',
        title: 'Stays fixed at {rate}',
        value: 'Fixed at {rate}',
        explain: 'Your rate does not change. Total interest is higher only because principal is repaid later.',
      },
      debt: {
        kicker: 'Principal still owing',
        title: 'Lower payments do not reduce what you owe',
        caption: 'Principal owing before the payment on {date}',
        explain: 'The {deferred} of postponed principal is still owing. It is repaid later, and the schedule now ends on {date}.',
        stepsTitle: 'How the postponed principal is repaid',
        steps: [
          { when: '{from} to {to}', text: 'Interest only. Principal stays at {opening}.' },
          { when: 'From {resume}', text: 'Principal payments of {monthly} a month resume.' },
          { when: 'Until {date}', text: 'The schedule runs {period} longer, so the {deferred} is fully repaid.' },
        ],
      },
    },
    actions: {
      seeDetailAria: 'See the detail: {item}',
      seeMonth: 'See the {month} payment',
      allChanges: 'See all changes',
      otherTitle: 'Explore the other items',
    },
    recon: {
      kicker: 'Reconciliation',
      title: 'Why {relief} and not {deferred}?',
      intro: 'Your payments from {from} to {to} are {relief} lower, not {deferred}. Here is how the two amounts reconcile.',
      deferred: 'Principal postponed',
      deferredSub: 'Still owing; repaid later',
      extra: 'More interest in the same months',
      extraSub: 'Principal is not reduced, so interest stays higher',
      relief: 'Lower payments, {from} to {to}',
      reliefSub: 'Temporary cash-flow relief',
      minus: 'minus',
      equals: 'equals',
      payments: 'Total payments, {from} to {to}',
      note: 'The {extra3} is already part of the {extra} of additional interest over the remaining schedule. It is not an extra cost on top of it.',
      sameAmount: 'In this example, the revised payments from {from} to {to} ({revised}) and the additional interest over the remaining schedule ({extra}) happen to be the same amount. They measure different things.',
      reliefLink: 'See the month-by-month difference',
    },
    unchanged: {
      title: 'Unchanged terms',
      intro: 'Everything below stays the same after the postponement.',
      rate: { label: 'Interest rate', value: '{rate}' },
      basis: { label: 'Rate type', value: 'Fixed rate, not affected by the postponement' },
      instalment: { label: 'Principal instalment once payments resume', value: '{amount} per month' },
      interestPaid: { label: 'Interest payments', value: 'Paid monthly, including during the postponement' },
      currency: { label: 'Currency', value: 'Canadian dollars ({code})' },
      loanId: { label: 'Loan identifier', value: '{id}' },
      acceptance: { label: 'Your acceptance', value: 'Not required through this notice', required: 'Required: see your notice' },
    },
    next: {
      title: 'What to do next',
      text: 'No acceptance is required through this notice. Review the revised schedule and update your [[cashFlow|cash-flow]] planning.',
      textRequired: 'Review the revised schedule and follow the instructions in your notice.',
      schedule: 'Review the revised schedule',
      notice: 'Read “What you need to do” in your notice',
    },
    detail: {
      definitionTitle: 'In plain language',
      actionsTitle: 'Explore, verify or ask',
      actionsIntro: 'Get a contextual explanation, read the formal wording or prepare a question for your representative.',
      monthsIntro: 'Each card compares the original and revised payment for the month.',
      titles: {
        principal: 'Your principal payments are postponed for {period}',
        interest: 'Interest is still paid monthly and costs more in total',
        'next-payment': 'Your next payment is {amount} on {date}',
        maturity: 'Your final payment moves to {date}',
        fees: 'No fee applies to this change',
        rate: 'Your interest rate stays fixed at {rate}',
        debt: 'Lower payments do not reduce what you owe',
      },
      intros: {
        principal: 'From {from} to {to}, you pay interest only. Principal payments of {amount} a month resume on {date}.',
        interest: 'During the postponement you pay {interest} of interest each month. Because principal is repaid later, total interest over the remaining schedule rises from {original} to {revised}.',
        'next-payment': 'Under the original schedule, this payment would have been {original}. It is lower because it covers interest only.',
        maturity: 'The original schedule ended on {original}. The revised schedule ends {period} later, with {count} payments instead of {originalCount}.',
        fees: 'The change fee in this fictional scenario is {fee}. The change still affects your total cost through additional interest.',
        rate: 'The same fixed rate applies to both schedules. What changes is the principal it applies to, month by month.',
        debt: 'Postponing principal moves {deferred} of repayments later in the schedule. That amount stays owing until it is repaid.',
      },
      breakdown: {
        principal: 'The postponed months and the first resumed payment',
        interest: 'Your first payments compared',
        'next-payment': 'How this payment is made up',
        maturity: 'The last payments compared',
        fees: 'What this change costs',
        rate: 'How monthly interest is calculated',
        debt: 'Principal owing at key dates',
      },
      definitions: {
        principal: 'Your [[principal|principal]] is the amount borrowed that remains to be repaid, not counting [[interest|interest]]. A [[postponement|principal postponement]] delays principal payments for a set period; interest is still paid.',
        interest: '[[interest|Interest]] is the cost of borrowing. Each month it is calculated on the [[outstanding|outstanding principal]] at the [[fixedRate|fixed rate]], so it stays higher while principal is not being repaid.',
        'next-payment': 'An [[instalment|instalment]] is a scheduled payment. During the [[postponement|postponement]], each instalment covers [[interest|interest]] only; once principal payments resume, it covers [[principal|principal]] and interest.',
        maturity: 'The [[maturity|maturity date]] is when the remaining loan balance is scheduled to be fully repaid. Repaying [[principal|principal]] later moves this date later.',
        fees: 'This change has no fee in this example, but it does change the total [[interest|interest]] you pay, because the [[outstanding|outstanding principal]] is repaid more slowly.',
        rate: 'A [[fixedRate|fixed rate]] does not change during the fixed-rate period. Your monthly [[interest|interest]] still depends on the [[outstanding|outstanding principal]] it applies to.',
        debt: '[[outstanding|Outstanding principal]] is the principal still owing at a given date. A [[postponement|principal postponement]] changes when you repay it, not how much [[principal|principal]] you repay.',
      },
      related: {
        principal: {
          title: 'Lower payments, same debt',
          body: [
            'Postponing {count} principal payments of {monthly} moves {deferred} of principal later in the schedule. It is still owing.',
            'Your payments from {from} to {to} are {relief} lower, not {deferred}, because interest stays at {interest} a month instead of decreasing.',
          ],
        },
        interest: {
          title: 'Why interest is higher',
          body: [
            'Under the original schedule, principal goes down by {monthly} each month, so interest falls a little every month.',
            'Under the revised schedule, principal stays at {opening} until {resume}, so interest stays at {interest} a month. The difference from {from} to {to} is {extra3}.',
            'Because the whole schedule shifts later, the extra interest continues until the end: {extra} in total, which already includes the {extra3}.',
          ],
        },
        'next-payment': {
          title: 'What happens next',
          body: [
            'Your payments on {d2} and {d3} are also {interest}. On {resume}, principal payments resume and your payment becomes {first}.',
            'These lower payments are temporary cash-flow relief. The postponed principal is still owing.',
          ],
        },
        maturity: {
          title: 'Why the final payment moves',
          body: [
            'Principal payments of {monthly} restart on {resume} instead of continuing from {firstDate}. Every later principal payment shifts by {period}.',
            'The schedule therefore needs {n} more monthly payments and ends on {date}. Interest continues on the principal still owing during those months.',
          ],
        },
        fees: {
          title: 'No fee does not mean no cost',
          body: [
            'No fee is charged for this change in this fictional scenario.',
            'The postponement still increases total interest over the remaining schedule by {extra}, and total remaining payments go from {originalTotal} to {revisedTotal}.',
          ],
        },
        rate: {
          title: 'Same rate, different interest',
          body: [
            'Your rate stays at {rate} under both schedules. This change does not reset, increase or reduce it.',
            'Monthly interest differs only because the principal the rate applies to is different: it is not reduced during the postponement.',
          ],
        },
        debt: {
          title: 'Why a temporary payment reduction is not a reduction in debt',
          body: [
            'During the postponement, you pay interest only. Your principal stays at {opening} instead of going down by {monthly} each month.',
            'After the {lastPostponed} payment, you still owe {deferred} more principal than under the original schedule: {revisedOwing} instead of {originalOwing}.',
            'That principal is repaid later. Principal payments of {monthly} resume on {resume} and continue until {date}, {period} later than originally scheduled.',
            'Because more principal is owing for longer, total interest over the remaining schedule is {extra} higher.',
            'Nothing is cancelled or written off: the principal you repay over the remaining schedule is {principal} under both schedules.',
          ],
        },
      },
      month: {
        paymentOn: 'Payment on {date}',
        postponed: 'Principal postponed',
        resumes: 'Principal resumes',
        added: 'Added payment',
        finalOriginal: 'Original final payment',
        finalRevised: 'Revised final payment',
        totalChange: 'Change in total payment',
        interestChange: 'Change in interest',
        none: 'No payment',
        noneNote: 'Already repaid under the original schedule.',
      },
      interestTotals: {
        title: 'Total interest over each complete remaining schedule',
        additional: 'Additional interest',
        sum: 'From {from} to {to}, the monthly interest differences add up to {extra3}.',
        within: 'That {extra3} is included in the {extra} of additional interest. It is not added to it.',
      },
      upcoming: {
        title: 'Your upcoming payments',
        interestOnly: 'Interest only',
        principalAndInterest: 'Principal and interest',
        originalWas: 'Original schedule: {amount}',
      },
      timeline: {
        title: 'Schedule length',
        original: 'Original: {count} payments, {from} to {to}',
        revised: 'Revised: {count} payments, {from} to {to}',
        added: '{period} added',
      },
      fees: {
        fee: 'Change fee',
        extra: 'Additional interest over the remaining schedule',
        totalOriginal: 'Total remaining payments, original schedule',
        totalRevised: 'Total remaining payments, revised schedule',
      },
      rate: {
        formula: 'Monthly interest = principal owing at the start of the month × {rate} ÷ 12',
        example: '{opening} × {rate} ÷ 12 = {interest}',
        rounding: 'Rounded half-up to the nearest cent, as set out in the assumptions of this illustration.',
        why: 'Same rate, higher principal: in {month}, interest is {revised} instead of {original} because no principal was repaid in {prev}.',
      },
      balance: {
        start: 'Start of the schedule, before the {date} payment',
        resume: 'Before the {date} payment, when principal payments resume',
        originalEnd: 'After the {date} payment, the original final payment',
        revisedEnd: 'After the {date} payment, the revised final payment',
        startNote: 'Same starting principal in both schedules.',
        resumeNote: '{amount} of postponed principal is still owing.',
        originalEndNote: 'Repaid in full under the original schedule; {amount} still to repay under the revised schedule.',
        revisedEndNote: 'Repaid in full under the revised schedule.',
        repaidOn: 'Repaid on {date}',
        scale: 'Bars are drawn to scale against the {amount} of principal at the start of the schedule.',
      },
    },
  },
  'fr-CA': {
    overline: 'Ce qui change',
    title: 'Ce qui change dans vos remboursements',
    intro: 'Vos remboursements de [[principal|capital]] de {months} sont reportés. Comparez chaque modalité avant et après la modification, voyez ce qui reste inchangé et comprenez pourquoi des versements moins élevés pendant quelques mois ne réduisent pas votre dette.',
    glance: {
      title: 'En bref',
      temporary: { label: 'Temporaire', text: 'Aucun remboursement de capital en {months}. Vous continuez de payer {interest} d’intérêts chaque mois.' },
      tradeoff: { label: 'Contrepartie', text: '{extra} d’intérêts de plus sur la durée restante du calendrier. Votre dernier versement est reporté au {date}.' },
      owing: { label: 'Toujours dû', text: 'Les {deferred} de capital reporté restent dus. Ils seront remboursés plus tard dans le calendrier.' },
    },
    groups: {
      changed: { title: 'Les modalités qui changent', intro: 'Chaque carte compare une modalité avant et après la modification.' },
      owing: { title: 'Ce que cela signifie pour votre dette', intro: 'Des versements moins élevés pendant {period} constituent un allègement temporaire de trésorerie. Ils ne réduisent pas votre dette.' },
      same: { title: 'Ce qui ne change pas', intro: 'Ces modalités ne sont pas touchées par le report.' },
    },
    schedule: { original: 'Calendrier initial', revised: 'Calendrier révisé' },
    badges: { notReduced: 'Dette non réduite' },
    cards: {
      principal: {
        kicker: 'Remboursements de capital',
        title: 'Reportés pendant {period}, puis repris',
        before: '{amount} par mois',
        beforeSub: 'plus les intérêts',
        after: '{zero} en {months}',
        afterSub: 'puis {amount} par mois à compter du {date}',
        explain: 'Le capital reporté n’est pas annulé. Il reste dû et sera remboursé plus tard dans le calendrier.',
      },
      interest: {
        kicker: 'Intérêts',
        title: 'Toujours payés chaque mois, et plus élevés au total',
        monthly: 'Intérêts mensuels, de {from} à {to}',
        afterNote: 'Même montant chaque mois, toujours payé mensuellement',
        total: 'Total des intérêts sur la durée restante',
        explain: 'Le capital ne diminue pas pendant le report : les intérêts restent donc à {interest} par mois et le calendrier restant coûte {extra} de plus en intérêts.',
        costLink: 'Comparer le coût total',
      },
      'next-payment': {
        kicker: 'Prochain versement',
        title: '{amount} le {date}',
        on: 'le {date}',
        explain: 'Ce versement couvre uniquement les intérêts. Les remboursements de capital reprennent le {date}; le versement sera alors de {amount}.',
      },
      maturity: {
        kicker: 'Date du dernier versement',
        title: 'Reportée de {period}',
        payments: '{count} versements mensuels',
        shift: '{period} plus tard',
        explain: 'Le remboursement du capital reprend plus tard; le calendrier se termine donc plus tard et compte maintenant {count} versements au lieu de {original}.',
        scheduleLink: 'Voir le calendrier complet',
      },
      fees: {
        kicker: 'Frais de modification',
        title: 'Aucuns frais pour cette modification',
        before: 'Aucuns frais de modification',
        beforeSub: 'avant cet avis',
        sub: 'frais liés à cette modification, dans ce scénario fictif',
        explain: 'Aucuns frais ne s’appliquent dans cet exemple. La modification a tout de même un coût : les intérêts additionnels présentés dans la carte Intérêts.',
      },
      rate: {
        kicker: 'Taux d’intérêt',
        title: 'Reste fixe à {rate}',
        value: 'Fixe à {rate}',
        explain: 'Votre taux ne change pas. Le total des intérêts est plus élevé uniquement parce que le capital est remboursé plus tard.',
      },
      debt: {
        kicker: 'Capital toujours dû',
        title: 'Des versements moins élevés ne réduisent pas votre dette',
        caption: 'Capital dû avant le versement du {date}',
        explain: 'Les {deferred} de capital reporté sont toujours dus. Ils seront remboursés plus tard, et le calendrier se termine maintenant le {date}.',
        stepsTitle: 'Comment le capital reporté est remboursé',
        steps: [
          { when: 'De {from} à {to}', text: 'Intérêts seulement. Le capital reste à {opening}.' },
          { when: 'À compter du {resume}', text: 'Reprise des remboursements de capital de {monthly} par mois.' },
          { when: 'Jusqu’au {date}', text: 'Le calendrier se prolonge de {period} pour que les {deferred} soient entièrement remboursés.' },
        ],
      },
    },
    actions: {
      seeDetailAria: 'Voir le détail : {item}',
      // {month} comes from App.ui.monthPhrase and already carries « de » / « d’ » (d’octobre 2031).
      seeMonth: 'Voir le versement {month}',
      allChanges: 'Voir tous les changements',
      otherTitle: 'Explorer les autres éléments',
    },
    recon: {
      kicker: 'Rapprochement',
      title: 'Pourquoi {relief} et non {deferred}?',
      intro: 'Vos versements de {from} à {to} diminuent de {relief}, et non de {deferred}. Voici comment concilier ces deux montants.',
      deferred: 'Capital reporté',
      deferredSub: 'Toujours dû; remboursé plus tard',
      extra: 'Intérêts de plus pendant ces mêmes mois',
      extraSub: 'Le capital ne diminue pas; les intérêts restent donc plus élevés',
      relief: 'Versements réduits, de {from} à {to}',
      reliefSub: 'Allègement temporaire de trésorerie',
      minus: 'moins',
      equals: 'égale',
      payments: 'Total des versements, de {from} à {to}',
      note: 'Les {extra3} font déjà partie des {extra} d’intérêts additionnels sur la durée restante. Ils ne s’ajoutent pas à ce montant.',
      sameAmount: 'Dans cet exemple, les versements révisés de {from} à {to} ({revised}) et les intérêts additionnels sur la durée restante ({extra}) correspondent par hasard au même montant. Ils mesurent des choses différentes.',
      reliefLink: 'Voir l’écart mois par mois',
    },
    unchanged: {
      title: 'Modalités inchangées',
      intro: 'Tous les éléments ci-dessous demeurent les mêmes après le report.',
      rate: { label: 'Taux d’intérêt', value: '{rate}' },
      basis: { label: 'Type de taux', value: 'Taux fixe, non touché par le report' },
      instalment: { label: 'Versement de capital à la reprise', value: '{amount} par mois' },
      interestPaid: { label: 'Paiement des intérêts', value: 'Chaque mois, y compris pendant le report' },
      currency: { label: 'Devise', value: 'Dollars canadiens ({code})' },
      loanId: { label: 'Numéro du prêt', value: '{id}' },
      acceptance: { label: 'Votre acceptation', value: 'Non requise dans le cadre de cet avis', required: 'Requise : consultez votre avis' },
    },
    next: {
      title: 'Prochaine étape',
      text: 'Aucune acceptation n’est requise dans le cadre de cet avis. Consultez le calendrier révisé et mettez à jour votre planification de [[cashFlow|trésorerie]].',
      textRequired: 'Consultez le calendrier révisé et suivez les instructions de votre avis.',
      schedule: 'Consulter le calendrier révisé',
      notice: 'Lire « Ce que vous devez faire » dans votre avis',
    },
    detail: {
      definitionTitle: 'En termes simples',
      actionsTitle: 'Explorer, vérifier ou poser une question',
      actionsIntro: 'Obtenez une explication contextuelle, lisez le libellé officiel ou préparez une question pour votre personne-ressource.',
      monthsIntro: 'Chaque carte compare le versement initial et le versement révisé du mois.',
      titles: {
        principal: 'Vos remboursements de capital sont reportés de {period}',
        interest: 'Les intérêts restent payables chaque mois et coûtent plus cher au total',
        'next-payment': 'Votre prochain versement est de {amount} le {date}',
        maturity: 'Votre dernier versement est reporté au {date}',
        fees: 'Aucuns frais ne s’appliquent à cette modification',
        rate: 'Votre taux d’intérêt reste fixe à {rate}',
        debt: 'Des versements moins élevés ne réduisent pas votre dette',
      },
      intros: {
        principal: 'De {from} à {to}, vous payez uniquement les intérêts. Les remboursements de capital de {amount} par mois reprennent le {date}.',
        interest: 'Pendant le report, vous payez {interest} d’intérêts chaque mois. Comme le capital est remboursé plus tard, le total des intérêts sur la durée restante passe de {original} à {revised}.',
        'next-payment': 'Selon le calendrier initial, ce versement aurait été de {original}. Il est moins élevé parce qu’il couvre uniquement les intérêts.',
        maturity: 'Le calendrier initial se terminait le {original}. Le calendrier révisé se termine {period} plus tard et compte {count} versements au lieu de {originalCount}.',
        fees: 'Les frais de modification dans ce scénario fictif sont de {fee}. La modification a tout de même une incidence sur votre coût total en raison des intérêts additionnels.',
        rate: 'Le même taux fixe s’applique aux deux calendriers. Ce qui change, c’est le capital auquel il s’applique, mois après mois.',
        debt: 'Le report déplace {deferred} de remboursements de capital plus tard dans le calendrier. Ce montant reste dû jusqu’à son remboursement.',
      },
      breakdown: {
        principal: 'Les mois reportés et le premier versement de reprise',
        interest: 'Comparaison de vos premiers versements',
        'next-payment': 'Composition de ce versement',
        maturity: 'Comparaison des derniers versements',
        fees: 'Ce que coûte cette modification',
        rate: 'Comment les intérêts mensuels sont calculés',
        debt: 'Capital dû à des dates clés',
      },
      definitions: {
        principal: 'Le [[principal|capital]] est le montant emprunté qui reste à rembourser, sans les [[interest|intérêts]]. Un [[postponement|report]] des remboursements de capital décale ces remboursements pendant une période déterminée; les intérêts restent payables.',
        interest: 'Les [[interest|intérêts]] représentent le coût de l’emprunt. Chaque mois, ils sont calculés sur le [[outstanding|capital restant à rembourser]] au [[fixedRate|taux fixe]]; ils restent donc plus élevés tant que le capital n’est pas remboursé.',
        'next-payment': 'Un [[instalment|versement]] est un paiement prévu au calendrier. Pendant le [[postponement|report]], chaque versement couvre uniquement les [[interest|intérêts]]; à la reprise, il couvre le [[principal|capital]] et les intérêts.',
        maturity: 'La [[maturity|date d’échéance]] est la date à laquelle le solde restant du prêt doit être entièrement remboursé. Rembourser le [[principal|capital]] plus tard repousse cette date.',
        fees: 'Cette modification n’entraîne aucuns frais dans cet exemple, mais elle change le total des [[interest|intérêts]] payés, car le [[outstanding|capital restant à rembourser]] diminue plus lentement.',
        rate: 'Un [[fixedRate|taux fixe]] ne change pas pendant la période à taux fixe. Vos [[interest|intérêts]] mensuels dépendent toutefois du [[outstanding|capital restant à rembourser]] auquel il s’applique.',
        debt: 'Le [[outstanding|capital restant à rembourser]] est le capital toujours dû à une date donnée. Un [[postponement|report]] des remboursements de capital change le moment où vous le remboursez, et non le montant de [[principal|capital]] à rembourser.',
      },
      related: {
        principal: {
          title: 'Des versements moins élevés, la même dette',
          body: [
            'Le report de {count} remboursements de capital de {monthly} déplace {deferred} de capital plus tard dans le calendrier. Ce montant reste dû.',
            'Vos versements de {from} à {to} diminuent de {relief}, et non de {deferred}, parce que les intérêts restent à {interest} par mois au lieu de diminuer.',
          ],
        },
        interest: {
          title: 'Pourquoi les intérêts sont plus élevés',
          body: [
            'Selon le calendrier initial, le capital diminue de {monthly} chaque mois; les intérêts baissent donc un peu chaque mois.',
            'Selon le calendrier révisé, le capital reste à {opening} jusqu’au {resume}; les intérêts restent donc à {interest} par mois. L’écart de {from} à {to} est de {extra3}.',
            'Comme tout le calendrier est décalé, les intérêts additionnels se poursuivent jusqu’à la fin : {extra} au total, ce qui comprend déjà les {extra3}.',
          ],
        },
        'next-payment': {
          title: 'La suite',
          body: [
            'Vos versements du {d2} et du {d3} sont aussi de {interest}. Le {resume}, les remboursements de capital reprennent et votre versement passe à {first}.',
            'Ces versements moins élevés constituent un allègement temporaire de trésorerie. Le capital reporté reste dû.',
          ],
        },
        maturity: {
          title: 'Pourquoi le dernier versement est reporté',
          body: [
            'Les remboursements de capital de {monthly} reprennent le {resume} au lieu de se poursuivre dès le {firstDate}. Chaque remboursement de capital suivant est décalé de {period}.',
            'Le calendrier compte donc {n} versements mensuels de plus et se termine le {date}. Des intérêts continuent de s’appliquer au capital toujours dû pendant ces mois.',
          ],
        },
        fees: {
          title: 'Aucuns frais ne veut pas dire aucun coût',
          body: [
            'Aucuns frais ne sont exigés pour cette modification dans ce scénario fictif.',
            'Le report augmente tout de même le total des intérêts sur la durée restante de {extra}, et le total des versements restants passe de {originalTotal} à {revisedTotal}.',
          ],
        },
        rate: {
          title: 'Même taux, intérêts différents',
          body: [
            'Votre taux demeure à {rate} dans les deux calendriers. Cette modification ne le réinitialise pas, ne l’augmente pas et ne le réduit pas.',
            'Les intérêts mensuels diffèrent uniquement parce que le capital auquel le taux s’applique est différent : il ne diminue pas pendant le report.',
          ],
        },
        debt: {
          title: 'Pourquoi une réduction temporaire des versements ne réduit pas votre dette',
          body: [
            'Pendant le report, vous payez uniquement les intérêts. Votre capital reste à {opening} au lieu de diminuer de {monthly} chaque mois.',
            'Après le versement du {lastPostponed}, vous devez encore {deferred} de capital de plus que selon le calendrier initial : {revisedOwing} au lieu de {originalOwing}.',
            'Ce capital est remboursé plus tard. Les remboursements de capital de {monthly} reprennent le {resume} et se poursuivent jusqu’au {date}, soit {period} plus tard que prévu initialement.',
            'Comme un capital plus élevé reste dû plus longtemps, le total des intérêts sur la durée restante augmente de {extra}.',
            'Aucun montant n’est annulé ni radié : le capital que vous remboursez sur la durée restante est de {principal} dans les deux calendriers.',
          ],
        },
      },
      month: {
        paymentOn: 'Versement du {date}',
        postponed: 'Capital reporté',
        resumes: 'Reprise du capital',
        added: 'Versement ajouté',
        finalOriginal: 'Dernier versement initial',
        finalRevised: 'Dernier versement révisé',
        totalChange: 'Variation du versement total',
        interestChange: 'Variation des intérêts',
        none: 'Aucun versement',
        noneNote: 'Déjà remboursé selon le calendrier initial.',
      },
      interestTotals: {
        title: 'Total des intérêts sur toute la durée restante de chaque calendrier',
        additional: 'Intérêts additionnels',
        sum: 'De {from} à {to}, les écarts d’intérêts mensuels totalisent {extra3}.',
        within: 'Ces {extra3} sont inclus dans les {extra} d’intérêts additionnels. Ils ne s’y ajoutent pas.',
      },
      upcoming: {
        title: 'Vos prochains versements',
        interestOnly: 'Intérêts seulement',
        principalAndInterest: 'Capital et intérêts',
        originalWas: 'Calendrier initial : {amount}',
      },
      timeline: {
        title: 'Durée du calendrier',
        original: 'Initial : {count} versements, de {from} à {to}',
        revised: 'Révisé : {count} versements, de {from} à {to}',
        added: '{period} de plus',
      },
      fees: {
        fee: 'Frais de modification',
        extra: 'Intérêts additionnels sur la durée restante',
        totalOriginal: 'Total des versements restants, calendrier initial',
        totalRevised: 'Total des versements restants, calendrier révisé',
      },
      rate: {
        formula: 'Intérêts mensuels = capital dû au début du mois × {rate} ÷ 12',
        example: '{opening} × {rate} ÷ 12 = {interest}',
        rounding: 'Intérêts arrondis au cent le plus proche (la demie étant arrondie au cent supérieur), selon les hypothèses de cette illustration.',
        why: 'Même taux, capital plus élevé : en {month}, les intérêts sont de {revised} au lieu de {original}, car aucun capital n’a été remboursé en {prev}.',
      },
      balance: {
        start: 'Début du calendrier, avant le versement du {date}',
        resume: 'Avant le versement du {date}, à la reprise des remboursements de capital',
        originalEnd: 'Après le versement du {date}, dernier versement du calendrier initial',
        revisedEnd: 'Après le versement du {date}, dernier versement du calendrier révisé',
        startNote: 'Même capital de départ dans les deux calendriers.',
        resumeNote: 'Il reste {amount} de capital reporté à rembourser.',
        originalEndNote: 'Entièrement remboursé selon le calendrier initial; il reste {amount} à rembourser selon le calendrier révisé.',
        revisedEndNote: 'Entièrement remboursé selon le calendrier révisé.',
        repaidOn: 'Remboursé le {date}',
        scale: 'Les barres sont proportionnelles au capital de {amount} au début du calendrier.',
      },
    },
  },
});
