/* Clair: approved demo-assistant copy (ApprovedContent).
 * Every amount and date is a {param} filled from App.record via App.fmt.
 * Answers explain this sample notice only; they never describe the
 * postponement as a reduction of debt, and the extra interest within the
 * postponement is always presented as part of the lifetime increase.
 * French drafts are implementation input pending qualified fr-CA review. */
App.i18n.register('clair', {
  'en-CA': {
    title: 'Clair — Your financing guide',
    status: 'Demo assistant • Answers from this sample notice • No live AI connection.',
    contextLabel: 'Asking about',
    contextRemove: 'Remove context: {item}',
    contextRemoved: 'Context removed. Clair will answer about the whole notice.',
    logLabel: 'Conversation with Clair',
    suggestedTitle: 'Suggested questions',
    inputLabel: 'Your question for Clair',
    placeholder: 'Ask a question…',
    hint: 'Answers come from this sample notice only. Don’t enter personal or account details.',
    send: 'Send',
    emptyError: 'Type a question first.',
    counter: '{n} of {max} characters',
    youSaid: 'You asked:',
    clairSaid: 'Clair answered:',
    explainPrefix: 'Explain: {item}',
    explainQuoted: 'Explain “{item}”',
    supportingFact: 'Supporting fact',
    seeInNotice: 'See in your notice: {title}',
    seeIn: 'See in “{section}”: {item}',
    seeInSection: 'Go to “{section}”',
    askPerson: 'Ask a person',
    inLanguage: 'In {language}',
    announce: 'Clair: {text}',
    and: 'and',
    greeting: 'Hello! I’m Clair, a demo guide to this sample financing notice. Ask what changed, what you pay and when, or pick a suggested question below.',

    suggestions: {
      whyRelief: 'Why isn’t the relief {deferred}?',
      nextPayment: 'When is my next payment?',
      totalCost: 'What’s the total extra cost?',
      acceptance: 'Do I need to accept anything?',
      whatChanged: 'What changed?',
      resume: 'When do principal payments resume?',
      maturity: 'When is my final payment now?',
      debtReduced: 'Is my debt reduced?',
      continuingInterest: 'Do I still pay interest?',
      rate: 'Does my interest rate change?',
      fees: 'Is there a fee?',
      unchanged: 'What stays the same?',
      postponementPeriod: 'Which months are postponed?',
      balanceAfter: 'What do I owe after the postponement?',
      capitalisedInterest: 'Is any interest capitalised?',
      principalMeaning: 'What does principal mean?',
      printExport: 'How do I print or export this?',
      queryPrep: 'How do I ask a person?',
      support: 'What support is available?',
      aboutClair: 'Is this a live AI?',
      purpose: 'Why did I receive this notice?',
      accountant: 'Can my accountant review it?',
    },

    answers: {
      whatChanged: 'Your principal payments for {months} are postponed. During those months you pay interest only: {postInterest} a month. Principal payments resume on {resumeDate}, your final payment moves to {revMat}, and the postponed principal remains owing.',
      purpose: 'This notice explains an approved change to your loan: you asked to postpone principal payments, and in this fictional scenario the change is approved and completed. It shows what changes, what stays the same and what to do next.',
      purposeSeasonal: 'This notice explains an approved change to your loan. In this fictional scenario, you asked to postpone principal payments to manage a planned seasonal inventory build. It shows what changes, what stays the same and what to do next.',
      effectiveDate: 'The change takes effect on {effective}. The first payment under the revised schedule is due on {nextDate}.',
      nextPayment: 'Your next payment is {revNext} on {nextDate}. It covers interest only, because principal is postponed that month.',
      postponementPeriod: 'Your principal payments for {months} are postponed. You still pay {postInterest} of interest in each of those months, and principal payments of {monthlyPrincipal} restart on {resumeDate}.',
      principalMeaning: 'Principal is the amount borrowed that remains to be repaid, not including interest. Here, {deferred} of principal is moved later in the schedule; it is still owed.',
      continuingInterest: 'Interest continues during the postponement at the same {rate} fixed rate. Because no principal is repaid in those months, you pay {postInterest} of interest each month; only principal is postponed.',
      whyRelief: '{deferred} of principal is delayed. Because that principal isn’t reduced, you pay {extra3} more interest within those months than in the original schedule. So your payments are {reduction} lower, not {deferred}, and the {deferred} of principal remains owing.',
      relief: 'From {from} to {to}, your payments total {revNear} instead of {origNear}: {reduction} lower. This is temporary cash-flow relief, not a reduction in what you owe. The postponed principal is still owed, and over the whole remaining term you pay {extraLife} more interest.',
      totalCost: 'The revised schedule adds {extraLife} of interest over the remaining term. The {extra3} of extra interest from {from} to {to} is already included in that amount, so it isn’t added again. There is no change fee.',
      maturity: 'Your final payment moves from {origMat} to {revMat}, because the postponed principal is repaid at the end of the schedule.',
      resume: 'Principal payments resume on {resumeDate}. That payment is {firstResumed}: {monthlyPrincipal} of principal plus {firstResumedInterest} of interest.',
      rate: 'Your fixed rate stays at {rate}; it doesn’t change. Total interest rises only because principal is repaid later.',
      fees: 'There is no fee for this change in this fictional scenario. The cost of the postponement is the additional interest of {extraLife} over the remaining term.',
      unchanged: 'Your {rate} fixed rate, the {monthlyPrincipal} monthly principal instalment once payments resume, and all other terms of loan {loanId} stay the same. There is no change fee.',
      acceptance: 'You don’t need to accept, sign or reply to anything through this notice; the change is already approved and completed in this fictional scenario. It’s a good idea to review the revised schedule and update your cash-flow planning.',
      printExport: 'In “{notice}”, choose “{print}” for a printable copy, or download the original or revised schedule as a CSV file. In “{payments}”, you can also download the selection you’re viewing.',
      queryPrep: 'Choose “{askItem}” beside any item, or “{askGeneral}” in “{help}”. You draft your question, review it, then create a local demo request. Nothing is sent to BDC in this demo.',
      support: 'The “{supportSection}” section lists optional BDC resources, such as financial management consulting for cash-flow planning. They’re separate from this notice and don’t imply eligibility or approval.',
      supportSuppressed: 'The “{supportSection}” section focuses on help and learning resources, such as cash-flow planning. They’re separate from this notice and don’t imply eligibility or approval.',
      debtReduced: 'The postponement delays {deferred} of principal; it doesn’t reduce or cancel your debt. You still owe the same principal, and it’s repaid later in the schedule.',
      capitalisedInterest: 'No interest is capitalised. Interest during the postponement is paid each month, so it isn’t added to the amount you owe.',
      balanceAfter: 'At the end of the postponement ({postEnd}), the revised schedule shows {revPostClose} of principal still owing, compared with {origPostClose} in the original schedule. This demo doesn’t show a live account balance.',
      accountant: 'You can share a printed copy or the CSV schedule with your accountant. In a live service, an authorised user could be given controlled access; this demo can’t grant access to anyone.',
      aboutClair: 'I’m Clair, a demo assistant. I answer from this sample notice using local rules: there’s no live AI connection, and what you type stays in this browser. I can’t see any real BDC records.',
      aboutDemo: 'Demo insights show local interaction counts from this browser tab only. They aren’t measured BDC outcomes, and nothing is sent anywhere.',
      greeting: 'Hello! Ask me anything about this sample notice, such as what changed or when your next payment is.',
      thanks: 'You’re welcome. Is there anything else in this notice I can explain?',
      scheduleClause: 'This schedule lists all {revCount} revised payments, from {nextDate} to {revMat}. The first payments are interest only; the rest include {monthlyPrincipal} of principal each month.',
      assumptions: 'The illustration assumes month-end payments, a fixed {rate} rate, no new advances or extra repayments, and no capitalised interest. These are simulation assumptions, not BDC servicing rules.',
      chartPayments: 'The chart compares monthly payments from {from} to {sixth}. In the revised schedule, the {from} to {to} payments are interest only ({postInterest}); from {resumeMonth}, payments include {monthlyPrincipal} of principal again.',
      chartBalance: 'In the revised schedule, principal stays at {principalStart} until the end of {postEnd}, then falls by {monthlyPrincipal} a month until {revMat}. In the original schedule, it reaches zero on {origMat}.',
      resourceFinancialManagement: 'Financial management consulting can help with cash-flow forecasting and working-capital planning. It’s optional support, separate from this notice, and doesn’t imply eligibility.',
      resourceFinancialManagementSeasonal: 'Financial management consulting can help with cash-flow forecasting and working-capital planning, which matters for a planned seasonal inventory build. It’s optional support, separate from this notice, and doesn’t imply eligibility.',
      resourceWorkingCapital: 'A Working Capital Loan is a separate BDC financing product, listed in “{supportSection}” for information only. It isn’t part of this notice, any financing is subject to assessment and approval, and I can’t assess eligibility.',
      resourceWorkingCapitalSuppressed: 'Additional borrowing isn’t promoted in this situation. If you’re facing difficulties, you can prepare a question for a person to discuss help.',
      resourceLearning: 'BDC’s cash-flow learning resources are educational. They can help you plan around lower payments from {from} to {to}, without any credit commitment.',
      limitChange: 'I can’t change your payments or loan terms; I can only explain this sample notice. If you’d like to discuss a change, you can prepare a question for a person.',
      limitApprove: 'I can’t approve another postponement or any other request. You can prepare a question for a person instead; in this demo, nothing is sent to BDC.',
      limitEligibility: 'I can’t assess eligibility or offer financing. The “{supportSection}” section describes optional BDC resources, and any financing is subject to assessment and approval. You can also prepare a question for a person.',
      limitEligibilitySuppressed: 'I can’t assess eligibility or offer financing. If you’re facing difficulties, you can prepare a question for a person to discuss help that fits your situation.',
      limitPay: 'I can’t process payments, and this demo has no payment function. Under the revised schedule, your next payment is {revNext} on {nextDate}.',
      unrelated: 'I can only help with this sample notice. Here are some things I can answer:',
      fallback: 'I can only answer questions about this sample notice — here are things I can help with:',
    },

    terms: {
      principal: 'In this notice, {deferred} of principal is moved later in the schedule; it is still owed.',
      interest: 'Interest continues during the postponement at the same {rate} rate.',
      postponement: 'Here, your principal payments for {months} are postponed.',
      instalment: 'Your monthly instalment is {postInterest} during the postponement, then {firstResumed} on {resumeDate}.',
      maturity: 'Your maturity date moves from {origMat} to {revMat}.',
      outstanding: 'The postponement keeps more principal outstanding for longer, which is why total interest increases.',
      fixedRate: 'Your fixed rate stays at {rate}.',
      cashFlow: 'The postponement lowers your payments from {from} to {to}, which eases cash flow in those months.',
      cashFlowSeasonal: 'The postponement lowers your payments from {from} to {to}, which can help with a seasonal inventory build.',
      amortisation: 'The revised schedule repays the same principal over {revCount} payments instead of {origCount}.',
      capitalisedInterest: 'Interest during the postponement is paid each month instead.',
    },

    facts: {
      counts: 'Original schedule: {origCount} payments, the last on {origMat}. Revised schedule: {revCount} payments, the last on {revMat}.',
      nextPayment: 'Original schedule: {origNextFull} ({origNextP} principal + {origNextI} interest). Revised schedule: {revNextFull} ({revNextP} principal + {revNextI} interest).',
      firstDue: 'Payment due {nextDate}: {origNextFull} in the original schedule, {revNextFull} in the revised schedule.',
      nearTerm: 'Payments from {from} to {to}: {origNearFull} in the original schedule, {revNearFull} in the revised schedule.',
      nearTermDiff: 'Payments from {from} to {to}: {origNearFull} in the original schedule, {revNearFull} in the revised schedule, or {reductionFull} lower.',
      principalOwing: 'Principal owing at the end of {postEnd}: {origPostCloseFull} in the original schedule, {revPostCloseFull} in the revised schedule.',
      interestMonth: 'Interest for {secondMonth}: {origSecondIFull} in the original schedule, {revSecondIFull} in the revised schedule.',
      totals: 'Total interest: {origIntFull} (original), {revIntFull} (revised). Total payments: {origTotalFull} (original), {revTotalFull} (revised).',
      interestTotals: 'Total interest: {origIntFull} in the original schedule, {revIntFull} in the revised schedule.',
      resume: 'Payment for {resumeMonth}: {origResFull} in the original schedule, {revResFull} in the revised schedule.',
      rate: 'Fixed rate: {rate} in both the original and revised schedules.',
      fees: 'Change fee: {feeFull}. Total payments: {origTotalFull} (original), {revTotalFull} (revised).',
      unchanged: 'Monthly principal instalment: {monthlyPrincipalFull} in both schedules; the revised schedule has {revCount} payments instead of {origCount}.',
      issued: 'Issued {issue}, effective {effective}. Final payment: {origMat} in the original schedule, {revMat} in the revised schedule.',
      exports: 'Print and CSV use the same approved schedules: {origCount} original payments and {revCount} revised payments.',
      ids: 'Your question can reference notice {noticeId} and loan {loanId}.',
      capitalised: 'Principal at the end of {postEnd}: {revPostCloseFull} in the revised schedule (unchanged since {effective}), {origPostCloseFull} in the original schedule.',
      startPrincipal: 'Principal at the start of both illustrated schedules ({effective}): {principalStartFull}.',
      scheduleTotals: 'Original schedule: {origCount} payments totalling {origTotalFull}. Revised schedule: {revCount} payments totalling {revTotalFull}.',
      assumptions: 'Both schedules start from {principalStartFull} of principal on {effective}; the original ends on {origMat}, the revised on {revMat}.',
      firstMonthPayment: 'Payment for {firstMonth}: {origNextFull} in the original schedule, {revNextFull} in the revised schedule.',
    },

    month: {
      post: '{month} is in the postponement period, so your revised payment is {rTotal}, interest only, instead of {oTotal}. The {oPrincipal} of principal isn’t skipped: it’s repaid later. Interest is {rInterest} rather than {oInterest} because the principal hasn’t been reduced.',
      postSame: '{month} is in the postponement period, so your revised payment is {rTotal}, interest only, instead of {oTotal}. The {oPrincipal} of principal isn’t skipped: it’s repaid later. Interest is the same in both schedules this month.',
      resume: 'Principal payments resume in {month}. Your revised payment is {rTotal} ({rPrincipal} principal plus {rInterest} interest), compared with {oTotal} in the original schedule. Interest is higher because the remaining principal is {rOpen} instead of {oOpen}.',
      resumed: 'In {month}, both schedules include {rPrincipal} of principal. The revised payment is {rTotal} instead of {oTotal}, because interest is charged on a higher remaining principal: {rOpen} instead of {oOpen}.',
      extension: '{month} comes after the original final payment on {origMat}. Under the revised schedule, you still pay {rTotal} this month as part of repaying the postponed principal.',
      final: '{month} is your final payment under the revised schedule: {rTotal} ({rPrincipal} principal plus {rInterest} interest). The original schedule ended on {origMat}.',
      outside: 'There’s no payment in {month} in either schedule. The illustrated payments run from {nextDate} to {revMat}.',
      fact: 'Original: {oPrincipal} principal + {oInterest} interest = {oTotal}. Revised: {rPrincipal} principal + {rInterest} interest = {rTotal}.',
      factExtension: 'Original: no payment (repaid by {origMat}). Revised: {rPrincipal} principal + {rInterest} interest = {rTotal}.',
      factOutside: 'Original: {origCount} payments to {origMat}. Revised: {revCount} payments to {revMat}.',
    },
  },

  'fr-CA': {
    title: 'Clair — Votre guide du financement',
    status: 'Assistant de démonstration • Réponses tirées de cet avis type • Aucune connexion à une IA en direct.',
    contextLabel: 'Sujet',
    contextRemove: 'Retirer le sujet : {item}',
    contextRemoved: 'Sujet retiré. Clair répondra au sujet de l’avis en entier.',
    logLabel: 'Conversation avec Clair',
    suggestedTitle: 'Questions suggérées',
    inputLabel: 'Votre question pour Clair',
    placeholder: 'Posez votre question…',
    hint: 'Les réponses proviennent uniquement de cet avis type. N’entrez aucun renseignement personnel ou bancaire.',
    send: 'Envoyer',
    emptyError: 'Saisissez d’abord une question.',
    counter: '{n} caractères sur {max}',
    youSaid: 'Votre question :',
    clairSaid: 'Réponse de Clair :',
    explainPrefix: 'Expliquer : {item}',
    explainQuoted: 'Expliquer « {item} »',
    supportingFact: 'Fait à l’appui',
    seeInNotice: 'Voir dans votre avis : {title}',
    seeIn: 'Voir dans « {section} » : {item}',
    seeInSection: 'Aller à « {section} »',
    askPerson: 'Demander à une personne',
    inLanguage: 'En {language}',
    announce: 'Clair : {text}',
    and: 'et',
    greeting: 'Bonjour! Je suis Clair, un guide de démonstration pour cet avis de financement type. Demandez-moi ce qui change, combien vous payez et quand, ou choisissez une question suggérée ci-dessous.',

    suggestions: {
      whyRelief: 'Pourquoi l’allègement n’est-il pas de {deferred}?',
      nextPayment: 'Quand aura lieu mon prochain versement?',
      totalCost: 'Quel est le coût supplémentaire total?',
      acceptance: 'Dois-je accepter quelque chose?',
      whatChanged: 'Qu’est-ce qui change?',
      resume: 'Quand les remboursements de capital reprennent-ils?',
      maturity: 'Quelle est maintenant la date de mon dernier versement?',
      debtReduced: 'Ma dette est-elle réduite?',
      continuingInterest: 'Est-ce que je paie encore des intérêts?',
      rate: 'Mon taux d’intérêt change-t-il?',
      fees: 'Y a-t-il des frais?',
      unchanged: 'Qu’est-ce qui ne change pas?',
      postponementPeriod: 'Quels mois sont visés par le report?',
      balanceAfter: 'Combien me restera-t-il à rembourser après le report?',
      capitalisedInterest: 'Des intérêts sont-ils capitalisés?',
      principalMeaning: 'Que veut dire « capital »?',
      printExport: 'Comment imprimer ou exporter cet avis?',
      queryPrep: 'Comment poser une question à une personne?',
      support: 'Quel soutien est offert?',
      aboutClair: 'Est-ce une IA en direct?',
      purpose: 'Pourquoi ai-je reçu cet avis?',
      accountant: 'Mon comptable peut-il l’examiner?',
    },

    answers: {
      whatChanged: 'Vos remboursements de capital de {months} sont reportés. Pendant ces mois, vous payez seulement les intérêts, soit {postInterest} par mois. Les remboursements de capital reprennent le {resumeDate}, votre dernier versement est reporté au {revMat}, et le capital reporté reste dû.',
      purpose: 'Cet avis explique une modification approuvée de votre prêt : vous avez demandé de reporter vos remboursements de capital et, dans ce scénario fictif, la modification est approuvée et finalisée. Il présente ce qui change, ce qui reste pareil et les prochaines étapes.',
      purposeSeasonal: 'Cet avis explique une modification approuvée de votre prêt. Dans ce scénario fictif, vous avez demandé de reporter vos remboursements de capital pour gérer une constitution de stocks saisonnière prévue. Il présente ce qui change, ce qui reste pareil et les prochaines étapes.',
      effectiveDate: 'La modification entre en vigueur le {effective}. Le premier versement selon le calendrier révisé est dû le {nextDate}.',
      nextPayment: 'Votre prochain versement est de {revNext}, le {nextDate}. Il ne comprend que les intérêts, puisque le remboursement du capital est reporté ce mois-là.',
      postponementPeriod: 'Vos remboursements de capital de {months} sont reportés. Vous payez quand même {postInterest} d’intérêts chacun de ces mois, et les remboursements de capital de {monthlyPrincipal} reprennent le {resumeDate}.',
      principalMeaning: 'Le capital est le montant emprunté qui reste à rembourser, sans les intérêts. Ici, {deferred} de capital seront remboursés plus tard dans le calendrier; ce montant reste dû.',
      continuingInterest: 'Les intérêts continuent de courir pendant le report, au même taux fixe de {rate}. Comme aucun capital n’est remboursé pendant ces mois, vous payez {postInterest} d’intérêts chaque mois; seul le capital est reporté.',
      whyRelief: 'Le remboursement de {deferred} de capital est retardé. Comme ce capital ne diminue pas, vous payez {extra3} d’intérêts de plus pendant ces mois que selon le calendrier initial. Vos versements diminuent donc de {reduction}, et non de {deferred}, et les {deferred} de capital restent dus.',
      relief: 'De {from} à {to}, vos versements totalisent {revNear} au lieu de {origNear}, soit {reduction} de moins. Il s’agit d’un allègement temporaire de trésorerie, et non d’une réduction de ce que vous devez. Le capital reporté reste dû et, sur toute la durée restante, vous payez {extraLife} d’intérêts de plus.',
      totalCost: 'Le calendrier révisé ajoute {extraLife} d’intérêts sur la durée restante. Les {extra3} d’intérêts supplémentaires de {from} à {to} sont déjà compris dans ce montant; ils ne s’y ajoutent pas. Il n’y a pas de frais de modification.',
      maturity: 'Votre dernier versement passe du {origMat} au {revMat}, puisque le capital reporté est remboursé à la fin du calendrier.',
      resume: 'Les remboursements de capital reprennent le {resumeDate}. Ce versement est de {firstResumed}, soit {monthlyPrincipal} de capital et {firstResumedInterest} d’intérêts.',
      rate: 'Votre taux fixe demeure à {rate}; il ne change pas. Le total des intérêts augmente seulement parce que le capital est remboursé plus tard.',
      fees: 'Il n’y a pas de frais pour cette modification dans ce scénario fictif. Le coût du report correspond aux intérêts additionnels de {extraLife} sur la durée restante.',
      unchanged: 'Votre taux fixe de {rate}, le versement mensuel de capital de {monthlyPrincipal} une fois les remboursements repris et toutes les autres modalités du prêt {loanId} restent les mêmes. Il n’y a pas de frais de modification.',
      acceptance: 'Vous n’avez rien à accepter ni à signer, et aucune réponse n’est requise dans le cadre de cet avis; la modification est déjà approuvée et finalisée dans ce scénario fictif. Il est conseillé de consulter le calendrier révisé et de mettre à jour votre planification de trésorerie.',
      printExport: 'Dans « {notice} », choisissez « {print} » pour obtenir une copie imprimable, ou téléchargez le calendrier initial ou révisé en format CSV. Dans « {payments} », vous pouvez aussi télécharger la sélection affichée.',
      queryPrep: 'Choisissez « {askItem} » à côté d’un élément, ou « {askGeneral} » dans « {help} ». Vous rédigez votre question, la vérifiez, puis créez une demande de démonstration locale. Rien n’est envoyé à BDC dans cette démo.',
      support: 'La section « {supportSection} » présente des ressources facultatives de BDC, comme la consultation en gestion financière pour planifier votre trésorerie. Elles sont distinctes de cet avis et n’impliquent aucune admissibilité ni approbation.',
      supportSuppressed: 'La section « {supportSection} » met l’accent sur l’aide et les ressources d’apprentissage, comme la planification de la trésorerie. Elles sont distinctes de cet avis et n’impliquent aucune admissibilité ni approbation.',
      debtReduced: 'Le report retarde le remboursement de {deferred} de capital; il ne réduit pas votre dette et ne l’annule pas. Vous devez toujours le même capital, qui sera remboursé plus tard dans le calendrier.',
      capitalisedInterest: 'Aucun intérêt n’est capitalisé. Les intérêts sont payés chaque mois pendant le report; ils ne s’ajoutent donc pas au montant dû.',
      balanceAfter: 'À la fin du report ({postEnd}), le calendrier révisé indique {revPostClose} de capital restant dû, contre {origPostClose} selon le calendrier initial. Cette démo n’affiche aucun solde de compte réel.',
      accountant: 'Vous pouvez remettre une copie imprimée ou le calendrier CSV à votre comptable. Dans un service réel, un utilisateur autorisé pourrait obtenir un accès contrôlé; cette démo ne peut accorder d’accès à personne.',
      aboutClair: 'Je suis Clair, un assistant de démonstration. Je réponds à partir de cet avis type selon des règles locales : il n’y a aucune connexion à une IA en direct, et ce que vous saisissez reste dans ce navigateur. Je n’ai accès à aucun dossier réel de BDC.',
      aboutDemo: 'L’aperçu de la démo présente seulement les interactions locales de cet onglet. Ce ne sont pas des résultats mesurés par BDC, et rien n’est transmis.',
      greeting: 'Bonjour! Posez-moi une question sur cet avis type, par exemple sur ce qui change ou sur la date de votre prochain versement.',
      thanks: 'Avec plaisir. Y a-t-il autre chose dans cet avis que je peux vous expliquer?',
      scheduleClause: 'Ce calendrier présente les {revCount} versements révisés, du {nextDate} au {revMat}. Les premiers versements ne comprennent que les intérêts; les suivants comprennent {monthlyPrincipal} de capital chaque mois.',
      assumptions: 'L’illustration suppose des versements en fin de mois, un taux fixe de {rate}, aucune nouvelle avance ni aucun remboursement supplémentaire, et aucun intérêt capitalisé. Ce sont des hypothèses de simulation, et non des règles de gestion des prêts de BDC.',
      chartPayments: 'Le graphique compare les versements mensuels de {from} à {sixth}. Selon le calendrier révisé, les versements de {from} à {to} ne comprennent que les intérêts ({postInterest}); à partir de {resumeMonth}, ils comprennent de nouveau {monthlyPrincipal} de capital.',
      chartBalance: 'Selon le calendrier révisé, le capital reste à {principalStart} jusqu’à la fin de {postEnd}, puis diminue de {monthlyPrincipal} par mois jusqu’au {revMat}. Selon le calendrier initial, il atteint zéro le {origMat}.',
      resourceFinancialManagement: 'La consultation en gestion financière peut aider à prévoir la trésorerie et à planifier le fonds de roulement. Il s’agit d’un soutien facultatif, distinct de cet avis, qui n’implique aucune admissibilité.',
      resourceFinancialManagementSeasonal: 'La consultation en gestion financière peut aider à prévoir la trésorerie et à planifier le fonds de roulement, ce qui est utile pour une constitution de stocks saisonnière prévue. Il s’agit d’un soutien facultatif, distinct de cet avis, qui n’implique aucune admissibilité.',
      resourceWorkingCapital: 'Le Prêt de fonds de roulement est un produit de financement distinct de BDC, présenté à titre informatif dans « {supportSection} ». Il ne fait pas partie de cet avis, tout financement est assujetti à une évaluation et à une approbation, et je ne peux pas évaluer votre admissibilité.',
      resourceWorkingCapitalSuppressed: 'L’emprunt supplémentaire n’est pas mis de l’avant dans cette situation. Si vous éprouvez des difficultés, vous pouvez préparer une question pour une personne afin de discuter de l’aide possible.',
      resourceLearning: 'Les ressources d’apprentissage de BDC sur la trésorerie sont éducatives. Elles peuvent vous aider à planifier en fonction de versements réduits de {from} à {to}, sans aucun engagement de crédit.',
      limitChange: 'Je ne peux pas modifier vos versements ni les modalités de votre prêt; je peux seulement expliquer cet avis type. Si vous souhaitez discuter d’une modification, vous pouvez préparer une question pour une personne.',
      limitApprove: 'Je ne peux pas approuver un autre report ni aucune autre demande. Vous pouvez plutôt préparer une question pour une personne; dans cette démo, rien n’est envoyé à BDC.',
      limitEligibility: 'Je ne peux pas évaluer votre admissibilité ni offrir du financement. La section « {supportSection} » décrit des ressources facultatives de BDC, et tout financement est assujetti à une évaluation et à une approbation. Vous pouvez aussi préparer une question pour une personne.',
      limitEligibilitySuppressed: 'Je ne peux pas évaluer votre admissibilité ni offrir du financement. Si vous éprouvez des difficultés, vous pouvez préparer une question pour une personne afin de discuter de l’aide adaptée à votre situation.',
      limitPay: 'Je ne peux pas traiter de paiements, et cette démo n’offre aucune fonction de paiement. Selon le calendrier révisé, votre prochain versement est de {revNext}, le {nextDate}.',
      unrelated: 'Je peux seulement vous aider avec cet avis type. Voici des questions auxquelles je peux répondre :',
      fallback: 'Je peux seulement répondre aux questions sur cet avis type — voici des sujets sur lesquels je peux vous aider :',
    },

    terms: {
      principal: 'Dans cet avis, {deferred} de capital seront remboursés plus tard dans le calendrier; ce montant reste dû.',
      interest: 'Les intérêts continuent de courir pendant le report, au même taux de {rate}.',
      postponement: 'Ici, vos remboursements de capital de {months} sont reportés.',
      instalment: 'Votre versement mensuel est de {postInterest} pendant le report, puis de {firstResumed} le {resumeDate}.',
      maturity: 'Votre date d’échéance passe du {origMat} au {revMat}.',
      outstanding: 'Le report maintient un capital restant plus élevé plus longtemps, ce qui explique la hausse du total des intérêts.',
      fixedRate: 'Votre taux fixe demeure à {rate}.',
      cashFlow: 'Le report réduit vos versements de {from} à {to}, ce qui allège votre trésorerie pendant ces mois.',
      cashFlowSeasonal: 'Le report réduit vos versements de {from} à {to}, ce qui peut faciliter une constitution de stocks saisonnière.',
      amortisation: 'Le calendrier révisé rembourse le même capital en {revCount} versements au lieu de {origCount}.',
      capitalisedInterest: 'Les intérêts du report sont plutôt payés chaque mois.',
    },

    facts: {
      counts: 'Calendrier initial : {origCount} versements, le dernier le {origMat}. Calendrier révisé : {revCount} versements, le dernier le {revMat}.',
      nextPayment: 'Calendrier initial : {origNextFull} ({origNextP} de capital + {origNextI} d’intérêts). Calendrier révisé : {revNextFull} ({revNextP} de capital + {revNextI} d’intérêts).',
      firstDue: 'Versement dû le {nextDate} : {origNextFull} selon le calendrier initial, {revNextFull} selon le calendrier révisé.',
      nearTerm: 'Versements de {from} à {to} : {origNearFull} selon le calendrier initial, {revNearFull} selon le calendrier révisé.',
      nearTermDiff: 'Versements de {from} à {to} : {origNearFull} selon le calendrier initial, {revNearFull} selon le calendrier révisé, soit {reductionFull} de moins.',
      principalOwing: 'Capital dû à la fin de {postEnd} : {origPostCloseFull} selon le calendrier initial, {revPostCloseFull} selon le calendrier révisé.',
      interestMonth: 'Intérêts de {secondMonth} : {origSecondIFull} selon le calendrier initial, {revSecondIFull} selon le calendrier révisé.',
      totals: 'Total des intérêts : {origIntFull} (initial), {revIntFull} (révisé). Total des versements : {origTotalFull} (initial), {revTotalFull} (révisé).',
      interestTotals: 'Total des intérêts : {origIntFull} selon le calendrier initial, {revIntFull} selon le calendrier révisé.',
      resume: 'Versement de {resumeMonth} : {origResFull} selon le calendrier initial, {revResFull} selon le calendrier révisé.',
      rate: 'Taux fixe : {rate} dans le calendrier initial comme dans le calendrier révisé.',
      fees: 'Frais de modification : {feeFull}. Total des versements : {origTotalFull} (initial), {revTotalFull} (révisé).',
      unchanged: 'Versement mensuel de capital : {monthlyPrincipalFull} dans les deux calendriers; le calendrier révisé compte {revCount} versements au lieu de {origCount}.',
      issued: 'Émis le {issue}, en vigueur le {effective}. Dernier versement : le {origMat} selon le calendrier initial, le {revMat} selon le calendrier révisé.',
      exports: 'L’impression et le fichier CSV reprennent les mêmes calendriers approuvés : {origCount} versements initiaux et {revCount} versements révisés.',
      ids: 'Votre question peut mentionner l’avis {noticeId} et le prêt {loanId}.',
      capitalised: 'Capital à la fin de {postEnd} : {revPostCloseFull} selon le calendrier révisé (inchangé depuis le {effective}), {origPostCloseFull} selon le calendrier initial.',
      startPrincipal: 'Capital au début des deux calendriers illustrés ({effective}) : {principalStartFull}.',
      scheduleTotals: 'Calendrier initial : {origCount} versements totalisant {origTotalFull}. Calendrier révisé : {revCount} versements totalisant {revTotalFull}.',
      assumptions: 'Les deux calendriers commencent avec {principalStartFull} de capital le {effective}; le calendrier initial se termine le {origMat}, le révisé le {revMat}.',
      firstMonthPayment: 'Versement de {firstMonth} : {origNextFull} selon le calendrier initial, {revNextFull} selon le calendrier révisé.',
    },

    month: {
      post: 'Le mois de {month} fait partie de la période de report : votre versement révisé est donc de {rTotal}, intérêts seulement, au lieu de {oTotal}. Les {oPrincipal} de capital ne sont pas annulés; ils seront remboursés plus tard. Les intérêts sont de {rInterest} plutôt que de {oInterest}, car le capital n’a pas diminué.',
      postSame: 'Le mois de {month} fait partie de la période de report : votre versement révisé est donc de {rTotal}, intérêts seulement, au lieu de {oTotal}. Les {oPrincipal} de capital ne sont pas annulés; ils seront remboursés plus tard. Les intérêts sont identiques dans les deux calendriers ce mois-ci.',
      resume: 'Les remboursements de capital reprennent en {month}. Votre versement révisé est de {rTotal} ({rPrincipal} de capital et {rInterest} d’intérêts), contre {oTotal} selon le calendrier initial. Les intérêts sont plus élevés, car le capital restant est de {rOpen} au lieu de {oOpen}.',
      resumed: 'En {month}, les deux calendriers comprennent {rPrincipal} de capital. Le versement révisé est de {rTotal} au lieu de {oTotal}, car les intérêts sont calculés sur un capital restant plus élevé : {rOpen} au lieu de {oOpen}.',
      extension: 'Le mois de {month} vient après le dernier versement initial du {origMat}. Selon le calendrier révisé, vous payez encore {rTotal} ce mois-ci pour rembourser le capital reporté.',
      final: 'Le versement de {month} est votre dernier versement selon le calendrier révisé : {rTotal} ({rPrincipal} de capital et {rInterest} d’intérêts). Le calendrier initial se terminait le {origMat}.',
      outside: 'Aucun versement n’est prévu en {month} dans l’un ou l’autre calendrier. Les versements illustrés vont du {nextDate} au {revMat}.',
      fact: 'Initial : {oPrincipal} de capital + {oInterest} d’intérêts = {oTotal}. Révisé : {rPrincipal} de capital + {rInterest} d’intérêts = {rTotal}.',
      factExtension: 'Initial : aucun versement (prêt remboursé au {origMat}). Révisé : {rPrincipal} de capital + {rInterest} d’intérêts = {rTotal}.',
      factOutside: 'Initial : {origCount} versements jusqu’au {origMat}. Révisé : {revCount} versements jusqu’au {revMat}.',
    },
  },
});
