/* Core approved content: shell, navigation, shared labels, item labels,
 * formal clause titles, video chapter titles and the glossary.
 * French drafts are implementation input pending qualified fr-CA review. */
App.i18n.register('common', {
  'en-CA': {
    docTitle: 'Important financing notice',
    close: 'Close',
    cancel: 'Cancel',
    back: 'Back',
    backTo: 'Back to {place}',
    breadcrumb: 'Return path',
    explainWithAI: 'Explain with AI',
    askAboutThis: 'Ask about this',
    askAQuestion: 'Ask a question',
    viewInNotice: 'View this in your notice',
    seeTheDetail: 'See the detail',
    seeInGlossary: 'See in glossary',
    definition: 'show definition',
    closeDefinition: 'Close definition',
    opensExternal: 'opens an external BDC website in a new tab',
    amountsInCAD: 'Amounts in Canadian dollars.',
    renderError: 'This section could not be displayed. Please choose another section.',
    timeLong: '{m} min {s} s',
    original: 'Original',
    revised: 'Revised',
    before: 'Before',
    after: 'After',
    difference: 'Difference',
    principal: 'Principal',
    interest: 'Interest',
    total: 'Total payment',
    openingBalance: 'Opening principal',
    closingBalance: 'Closing principal',
    noPayment: 'No payment (loan already repaid under the original schedule)',
    download: 'Download',
    copy: 'Copy',
    copied: 'Copied',
    copyFailed: 'Copy not available in this browser',
    print: 'Print / Save as PDF',
    languageNames: { 'en-CA': 'English', 'fr-CA': 'French' },
    writtenIn: 'Written in {language}',
    badges: {
      changed: 'Changed',
      unchanged: 'Unchanged',
      temporary: 'Temporary',
      later: 'Later date',
    },
    perMonth: 'per month',
    months: { one: '{n} month', other: '{n} months' },
    labelWithItem: '{label}: {item}',
  },
  'fr-CA': {
    docTitle: 'Avis important concernant votre financement',
    close: 'Fermer',
    cancel: 'Annuler',
    back: 'Retour',
    backTo: 'Retour à {place}',
    breadcrumb: 'Chemin de retour',
    explainWithAI: 'Expliquer avec l’IA',
    askAboutThis: 'Poser une question à ce sujet',
    askAQuestion: 'Poser une question',
    viewInNotice: 'Voir dans votre avis',
    seeTheDetail: 'Voir le détail',
    seeInGlossary: 'Voir dans le glossaire',
    definition: 'afficher la définition',
    closeDefinition: 'Fermer la définition',
    opensExternal: 'ouvre un site Web externe de BDC dans un nouvel onglet',
    amountsInCAD: 'Montants en dollars canadiens.',
    renderError: 'Cette section ne peut pas être affichée. Veuillez choisir une autre section.',
    timeLong: '{m} min {s} s',
    original: 'Initial',
    revised: 'Révisé',
    before: 'Avant',
    after: 'Après',
    difference: 'Écart',
    principal: 'Capital',
    interest: 'Intérêts',
    total: 'Versement total',
    openingBalance: 'Capital au début',
    closingBalance: 'Capital à la fin',
    noPayment: 'Aucun versement (prêt déjà remboursé selon le calendrier initial)',
    download: 'Télécharger',
    copy: 'Copier',
    copied: 'Copié',
    copyFailed: 'Copie non disponible dans ce navigateur',
    print: 'Imprimer / Enregistrer en PDF',
    languageNames: { 'en-CA': 'anglais', 'fr-CA': 'français' },
    writtenIn: 'Rédigé en {language}',
    badges: {
      changed: 'Modifié',
      unchanged: 'Inchangé',
      temporary: 'Temporaire',
      later: 'Date ultérieure',
    },
    perMonth: 'par mois',
    months: { one: '{n} mois', other: '{n} mois' },
    labelWithItem: '{label} : {item}',
  },
});

App.i18n.register('shell', {
  'en-CA': {
    descriptor: 'Important financing notice',
    descriptorMeta: 'Notice {notice}',
    logoPlaceholder: 'BDC logo placeholder',
    skip: 'Skip to main content',
    sectionsLabel: 'Notice sections',
    sectionsButton: 'Sections: {section}',
    current: '(current section)',
    languageChanged: 'Language changed to English.',
    launcherSub: 'Your financing guide',
    demoInsights: 'Session insights',
    resetDemo: 'Clear my activity',
    resetTitle: 'Clear your activity?',
    resetBody: 'This clears what you did in this browser tab: questions you prepared, your feedback, the Clair conversation and “Mark as reviewed”. Your notice does not change.',
    resetConfirm: 'Clear activity',
    resetDone: 'Your activity in this tab was cleared.',
    footerMeta: 'Notice {notice} · Loan {loan} · Record version {record}',
    footerPrivacy: 'What you type on this page stays in this browser tab unless you choose to download, print or share it.',
  },
  'fr-CA': {
    descriptor: 'Avis important concernant votre financement',
    descriptorMeta: 'Avis {notice}',
    logoPlaceholder: 'Espace réservé au logo de BDC',
    skip: 'Passer au contenu principal',
    sectionsLabel: 'Sections de l’avis',
    sectionsButton: 'Sections\u00a0: {section}',
    current: '(section actuelle)',
    languageChanged: 'La langue est maintenant le français.',
    launcherSub: 'Votre guide du financement',
    demoInsights: 'Statistiques de la séance',
    resetDemo: 'Effacer mon activité',
    resetTitle: 'Effacer votre activité?',
    resetBody: 'Cette action efface ce que vous avez fait dans cet onglet\u00a0: les questions préparées, vos commentaires, la conversation avec Clair et la mention «\u00a0Marquer comme consulté\u00a0». Votre avis ne change pas.',
    resetConfirm: 'Effacer l’activité',
    resetDone: 'Votre activité dans cet onglet a été effacée.',
    footerMeta: 'Avis {notice} · Prêt {loan} · Version du dossier {record}',
    footerPrivacy: 'Ce que vous saisissez sur cette page reste dans cet onglet, sauf si vous choisissez de le télécharger, de l’imprimer ou de le communiquer.',
  },
});

App.i18n.register('nav', {
  'en-CA': {
    overview: 'Overview',
    changes: 'What changed',
    payments: 'Payments & impact',
    documents: 'Your notice',
    support: 'Support for you',
    help: 'Help & questions',
    insights: 'Session insights',
  },
  'fr-CA': {
    overview: 'Aperçu',
    changes: 'Ce qui change',
    payments: 'Versements et incidence',
    documents: 'Votre avis',
    support: 'Du soutien pour vous',
    help: 'Aide et questions',
    insights: 'Statistiques de la séance',
  },
});

App.i18n.register('items', {
  'en-CA': {
    general: 'This notice (general question)',
    month: '{month} payment',
    clause: 'Notice clause: {title}',
    term: 'Glossary term: {term}',
    chapter: 'Video chapter: {title}',
    faq: 'Frequently asked question',
    card: {
      principal: 'Principal payments',
      interest: 'Interest',
      'next-payment': 'Next payment',
      maturity: 'Final payment date (maturity)',
      fees: 'Change fee',
      rate: 'Interest rate (unchanged)',
      debt: 'Principal still owing',
    },
    summary: {
      'next-payment': 'Next payment: {date}',
      resume: 'Principal payments resume',
      relief: 'Lower payments, November to January',
      'extra-interest': 'Additional interest over the remaining schedule',
    },
    resource: {
      'financial-management': 'Financial management consulting',
      'working-capital': 'Working Capital Loan',
      learning: 'BDC cash-flow learning resources',
    },
    chart: {
      payments: 'Payment comparison chart, November to April',
      balance: 'Principal balance chart',
    },
    infographic: {
      relief: 'Cash-flow effect, November to January',
      cost: 'Total additional interest',
    },
  },
  'fr-CA': {
    general: 'Cet avis (question générale)',
    month: 'Versement {month}',
    clause: 'Clause de l’avis : {title}',
    term: 'Terme du glossaire : {term}',
    chapter: 'Chapitre vidéo : {title}',
    faq: 'Question fréquente',
    card: {
      principal: 'Remboursements de capital',
      interest: 'Intérêts',
      'next-payment': 'Prochain versement',
      maturity: 'Date du dernier versement (échéance)',
      fees: 'Frais de modification',
      rate: 'Taux d’intérêt (inchangé)',
      debt: 'Capital toujours dû',
    },
    summary: {
      'next-payment': 'Prochain versement : {date}',
      resume: 'Reprise des remboursements de capital',
      relief: 'Versements réduits, de novembre à janvier',
      'extra-interest': 'Intérêts additionnels sur la durée restante',
    },
    resource: {
      'financial-management': 'Consultation en gestion financière',
      'working-capital': 'Prêt de fonds de roulement',
      learning: 'Ressources d’apprentissage de BDC sur la trésorerie',
    },
    chart: {
      payments: 'Graphique comparatif des versements, de novembre à avril',
      balance: 'Graphique du capital restant',
    },
    infographic: {
      relief: 'Effet sur la trésorerie, de novembre à janvier',
      cost: 'Total des intérêts additionnels',
    },
  },
});

App.i18n.register('clauses', {
  'en-CA': {
    purpose: '1. Purpose of this notice',
    amendment: '2. Amendment summary',
    postponement: '3. Principal postponement period',
    interest: '4. Interest during the postponement',
    resumption: '5. Resumption of principal payments',
    maturity: '6. Revised maturity date',
    cost: '7. Effect on interest and total payments',
    unchanged: '8. Terms that remain unchanged',
    action: '9. What you need to do',
    schedule: '10. Revised repayment schedule',
    assumptions: '11. Calculation basis',
    contact: '12. Questions and support',
  },
  'fr-CA': {
    purpose: '1. Objet du présent avis',
    amendment: '2. Résumé de la modification',
    postponement: '3. Période de report des remboursements de capital',
    interest: '4. Intérêts pendant le report',
    resumption: '5. Reprise des remboursements de capital',
    maturity: '6. Date d’échéance révisée',
    cost: '7. Incidence sur les intérêts et le total des versements',
    unchanged: '8. Modalités inchangées',
    action: '9. Ce que vous devez faire',
    schedule: '10. Calendrier de remboursement révisé',
    assumptions: '11. Base de calcul',
    contact: '12. Questions et soutien',
  },
});

App.i18n.register('chapters', {
  'en-CA': {
    welcome: 'A personal welcome',
    relief: 'Three months of breathing room',
    difference: 'Where the difference comes from',
    tradeoff: 'The trade-off',
    resume: 'Returning to principal payments',
    'next-step': 'Your next step',
  },
  'fr-CA': {
    welcome: 'Un mot de bienvenue',
    relief: 'Trois mois de répit',
    difference: 'D’où vient l’écart',
    tradeoff: 'La contrepartie',
    resume: 'La reprise des remboursements de capital',
    'next-step': 'Votre prochaine étape',
  },
});

App.i18n.register('glossary', {
  'en-CA': {
    title: 'Glossary',
    principal: { term: 'Principal', definition: 'The amount borrowed that remains to be repaid, excluding interest.' },
    interest: { term: 'Interest', definition: 'The cost of borrowing, calculated using the balance and the applicable rate.' },
    postponement: { term: 'Principal postponement', definition: 'Delaying principal payments for a set period. Interest may still be payable during that time.' },
    instalment: { term: 'Instalment', definition: 'A scheduled payment under the financing arrangement.' },
    maturity: { term: 'Maturity date', definition: 'The date the remaining loan balance is scheduled to be fully repaid.' },
    outstanding: { term: 'Outstanding principal', definition: 'Principal still owing at the relevant date.' },
    fixedRate: { term: 'Fixed rate', definition: 'A rate that does not change during the specified fixed-rate period.' },
    cashFlow: { term: 'Cash flow', definition: 'Money coming into and going out of the business.' },
    amortisation: { term: 'Amortisation', definition: 'Repayment of principal over a schedule.' },
    capitalisedInterest: { term: 'Capitalised interest', definition: 'Interest added to the amount owing. This does not apply to your amendment.' },
  },
  'fr-CA': {
    title: 'Glossaire',
    principal: { term: 'Capital', definition: 'Le montant emprunté qui reste à rembourser, sans les intérêts.' },
    interest: { term: 'Intérêts', definition: 'Le coût de l’emprunt, calculé à partir du solde et du taux applicable.' },
    postponement: { term: 'Report des remboursements de capital', definition: 'Le fait de reporter les remboursements de capital pendant une période déterminée. Des intérêts peuvent rester payables pendant cette période.' },
    instalment: { term: 'Versement', definition: 'Un paiement prévu au calendrier dans le cadre de l’entente de financement.' },
    maturity: { term: 'Date d’échéance', definition: 'La date à laquelle le solde restant du prêt doit être entièrement remboursé.' },
    outstanding: { term: 'Capital restant à rembourser', definition: 'Le capital toujours dû à une date donnée.' },
    fixedRate: { term: 'Taux fixe', definition: 'Un taux qui ne change pas pendant la période à taux fixe indiquée.' },
    cashFlow: { term: 'Trésorerie', definition: 'L’argent qui entre dans l’entreprise et qui en sort.' },
    amortisation: { term: 'Amortissement', definition: 'Le remboursement du capital selon un calendrier.' },
    capitalisedInterest: { term: 'Intérêts capitalisés', definition: 'Des intérêts ajoutés au montant dû. Cela ne s’applique pas à votre modification.' },
  },
});
