/* Core approved content: shell, navigation, shared labels, item labels,
 * formal clause titles, video chapter titles and the glossary.
 * French drafts are implementation input pending qualified fr-CA review. */
App.i18n.register('common', {
  'en-CA': {
    docTitle: 'Important financing notice (concept demonstration)',
    close: 'Close',
    cancel: 'Cancel',
    back: 'Back',
    backTo: 'Back to {place}',
    breadcrumb: 'Return path',
    explainWithAI: 'Explain with AI',
    askAboutThis: 'Ask about this',
    askAQuestion: 'Ask a question',
    viewInNotice: 'View this in your notice',
    seeTheDetail: 'See the detail',
    seeInGlossary: 'See in glossary',
    definition: 'show definition',
    closeDefinition: 'Close definition',
    opensExternal: 'opens an external BDC website in a new tab',
    illustrativeNote: 'Illustrative financing schedule, not a BDC offer.',
    amountsInCAD: 'Amounts in Canadian dollars.',
    renderError: 'This section could not be displayed. Please choose another section.',
    timeLong: '{m} min {s} s',
    original: 'Original',
    revised: 'Revised',
    before: 'Before',
    after: 'After',
    difference: 'Difference',
    principal: 'Principal',
    interest: 'Interest',
    total: 'Total payment',
    openingBalance: 'Opening principal',
    closingBalance: 'Closing principal',
    noPayment: 'No payment (loan already repaid under the original schedule)',
    download: 'Download',
    copy: 'Copy',
    copied: 'Copied',
    copyFailed: 'Copy not available in this browser',
    print: 'Print / Save as PDF',
    demoLabel: 'Demo',
    languageNames: { 'en-CA': 'English', 'fr-CA': 'French' },
    writtenIn: 'Written in {language}',
    badges: {
      changed: 'Changed',
      unchanged: 'Unchanged',
      temporary: 'Temporary',
      later: 'Later date',
      demo: 'Demo',
    },
    perMonth: 'per month',
    months: { one: '{n} month', other: '{n} months' },
    labelWithItem: '{label}: {item}',
  },
  'fr-CA': {
    docTitle: 'Avis important concernant votre financement (démonstration conceptuelle)',
    close: 'Fermer',
    cancel: 'Annuler',
    back: 'Retour',
    backTo: 'Retour à {place}',
    breadcrumb: 'Chemin de retour',
    explainWithAI: 'Expliquer avec l’IA',
    askAboutThis: 'Poser une question à ce sujet',
    askAQuestion: 'Poser une question',
    viewInNotice: 'Voir dans votre avis',
    seeTheDetail: 'Voir le détail',
    seeInGlossary: 'Voir dans le glossaire',
    definition: 'afficher la définition',
    closeDefinition: 'Fermer la définition',
    opensExternal: 'ouvre un site Web externe de BDC dans un nouvel onglet',
    illustrativeNote: 'Calendrier de financement illustratif, et non une offre de BDC.',
    amountsInCAD: 'Montants en dollars canadiens.',
    renderError: 'Cette section ne peut pas être affichée. Veuillez choisir une autre section.',
    timeLong: '{m} min {s} s',
    original: 'Initial',
    revised: 'Révisé',
    before: 'Avant',
    after: 'Après',
    difference: 'Écart',
    principal: 'Capital',
    interest: 'Intérêts',
    total: 'Versement total',
    openingBalance: 'Capital au début',
    closingBalance: 'Capital à la fin',
    noPayment: 'Aucun versement (prêt déjà remboursé selon le calendrier initial)',
    download: 'Télécharger',
    copy: 'Copier',
    copied: 'Copié',
    copyFailed: 'Copie non disponible dans ce navigateur',
    print: 'Imprimer / Enregistrer en PDF',
    demoLabel: 'Démo',
    languageNames: { 'en-CA': 'anglais', 'fr-CA': 'français' },
    writtenIn: 'Rédigé en {language}',
    badges: {
      changed: 'Modifié',
      unchanged: 'Inchangé',
      temporary: 'Temporaire',
      later: 'Date ultérieure',
      demo: 'Démo',
    },
    perMonth: 'par mois',
    months: { one: '{n} mois', other: '{n} mois' },
    labelWithItem: '{label} : {item}',
  },
});

App.i18n.register('shell', {
  'en-CA': {
    banner: 'Concept demonstration • Fictional client and financing terms • Not connected to BDC.',
    descriptor: 'Important financing notice',
    descriptorMeta: 'Notice {notice}',
    demoPill: 'Demo',
    logoPlaceholder: 'BDC logo placeholder',
    skip: 'Skip to main content',
    sectionsLabel: 'Notice sections',
    sectionsButton: 'Sections: {section}',
    current: '(current section)',
    languageChanged: 'Language changed to English.',
    launcherSub: 'Your financing guide',
    demoInsights: 'Demo insights',
    resetDemo: 'Reset demo',
    resetTitle: 'Reset this demonstration?',
    resetBody: 'This clears the local demo events, any drafted or created demo requests, survey responses, the Clair conversation and “Mark as reviewed”. The notice itself does not change.',
    resetConfirm: 'Reset demo',
    resetDone: 'The demonstration was reset.',
    footerData: 'This single file contains fictional data only. No information you enter leaves this browser, except when you choose to open an external BDC link. The accessibility widget is the one online service this page loads automatically.',
    aboutTitle: 'About this demonstration',
    aboutBody: [
      'Concept prototype of an interactive financing notice. Camille Roy, Atelier Boréal Inc., the loan and all amounts are fictional. Nothing here is a BDC offer, agreement, policy or system.',
      'Clair is a proposed demo name. In this file it answers only from this sample notice using local rules; there is no live AI connection.',
      'The narration was generated before distribution with ElevenLabs text-to-speech and is embedded in this file. Playback never contacts ElevenLabs.',
      'Demo requests, survey answers and “Mark as reviewed” stay in this browser tab and are cleared when you reset or close it.',
    ],
    buildInfo: 'Build {version} · {date} · Notice {notice} · Record version {record}',
  },
  'fr-CA': {
    banner: 'Démonstration conceptuelle • Clientèle et modalités fictives • Aucun lien avec les systèmes de BDC.',
    descriptor: 'Avis important concernant votre financement',
    descriptorMeta: 'Avis {notice}',
    demoPill: 'Démo',
    logoPlaceholder: 'Espace réservé au logo de BDC',
    skip: 'Passer au contenu principal',
    sectionsLabel: 'Sections de l’avis',
    sectionsButton: 'Sections : {section}',
    current: '(section actuelle)',
    languageChanged: 'La langue est maintenant le français.',
    launcherSub: 'Votre guide du financement',
    demoInsights: 'Statistiques de la démo',
    resetDemo: 'Réinitialiser la démo',
    resetTitle: 'Réinitialiser cette démonstration?',
    resetBody: 'Cette action efface les événements locaux de la démo, les demandes de démonstration rédigées ou créées, les réponses au sondage, la conversation avec Clair et la mention « Marquer comme consulté ». L’avis lui-même ne change pas.',
    resetConfirm: 'Réinitialiser la démo',
    resetDone: 'La démonstration a été réinitialisée.',
    footerData: 'Ce fichier unique contient uniquement des données fictives. Aucune information saisie ne quitte ce navigateur, sauf si vous choisissez d’ouvrir un lien externe de BDC. Le module d’accessibilité est le seul service en ligne que cette page charge automatiquement.',
    aboutTitle: 'À propos de cette démonstration',
    aboutBody: [
      'Prototype conceptuel d’un avis de financement interactif. Camille Roy, Atelier Boréal Inc., le prêt et tous les montants sont fictifs. Rien ici ne constitue une offre, une entente, une politique ou un système de BDC.',
      'Clair est un nom proposé pour la démo. Dans ce fichier, Clair répond uniquement à partir de cet avis type, selon des règles locales; il n’y a aucune connexion à une IA en direct.',
      'La narration a été générée avant la distribution avec la synthèse vocale d’ElevenLabs et est intégrée à ce fichier. La lecture ne communique jamais avec ElevenLabs.',
      'Les demandes de démonstration, les réponses au sondage et la mention « Marquer comme consulté » restent dans cet onglet et sont effacées lorsque vous réinitialisez la démo ou fermez l’onglet.',
    ],
    buildInfo: 'Version {version} · {date} · Avis {notice} · Version du dossier {record}',
  },
});

App.i18n.register('nav', {
  'en-CA': {
    overview: 'Overview',
    changes: 'What changed',
    payments: 'Payments & impact',
    documents: 'Your notice',
    support: 'Support for you',
    help: 'Help & questions',
    insights: 'Demo insights',
  },
  'fr-CA': {
    overview: 'Aperçu',
    changes: 'Ce qui change',
    payments: 'Versements et incidence',
    documents: 'Votre avis',
    support: 'Du soutien pour vous',
    help: 'Aide et questions',
    insights: 'Statistiques de la démo',
  },
});

App.i18n.register('items', {
  'en-CA': {
    general: 'This notice (general question)',
    month: '{month} payment',
    clause: 'Notice clause: {title}',
    term: 'Glossary term: {term}',
    chapter: 'Video chapter: {title}',
    faq: 'Frequently asked question',
    card: {
      principal: 'Principal payments',
      interest: 'Interest',
      'next-payment': 'Next payment',
      maturity: 'Final payment date (maturity)',
      fees: 'Change fee',
      rate: 'Interest rate (unchanged)',
      debt: 'Principal still owing',
    },
    summary: {
      'next-payment': 'Next payment: {date}',
      resume: 'Principal payments resume',
      relief: 'Lower payments, November to January',
      'extra-interest': 'Additional interest over the remaining schedule',
    },
    resource: {
      'financial-management': 'Financial management consulting',
      'working-capital': 'Working Capital Loan',
      learning: 'BDC cash-flow learning resources',
    },
    chart: {
      payments: 'Payment comparison chart, November to April',
      balance: 'Principal balance chart',
    },
    infographic: {
      relief: 'Cash-flow effect, November to January',
      cost: 'Total additional interest',
    },
  },
  'fr-CA': {
    general: 'Cet avis (question générale)',
    month: 'Versement {month}',
    clause: 'Clause de l’avis : {title}',
    term: 'Terme du glossaire : {term}',
    chapter: 'Chapitre vidéo : {title}',
    faq: 'Question fréquente',
    card: {
      principal: 'Remboursements de capital',
      interest: 'Intérêts',
      'next-payment': 'Prochain versement',
      maturity: 'Date du dernier versement (échéance)',
      fees: 'Frais de modification',
      rate: 'Taux d’intérêt (inchangé)',
      debt: 'Capital toujours dû',
    },
    summary: {
      'next-payment': 'Prochain versement : {date}',
      resume: 'Reprise des remboursements de capital',
      relief: 'Versements réduits, de novembre à janvier',
      'extra-interest': 'Intérêts additionnels sur la durée restante',
    },
    resource: {
      'financial-management': 'Consultation en gestion financière',
      'working-capital': 'Prêt de fonds de roulement',
      learning: 'Ressources d’apprentissage de BDC sur la trésorerie',
    },
    chart: {
      payments: 'Graphique comparatif des versements, de novembre à avril',
      balance: 'Graphique du capital restant',
    },
    infographic: {
      relief: 'Effet sur la trésorerie, de novembre à janvier',
      cost: 'Total des intérêts additionnels',
    },
  },
});

App.i18n.register('clauses', {
  'en-CA': {
    purpose: '1. Purpose of this notice',
    amendment: '2. Amendment summary',
    postponement: '3. Principal postponement period',
    interest: '4. Interest during the postponement',
    resumption: '5. Resumption of principal payments',
    maturity: '6. Revised maturity date',
    cost: '7. Effect on interest and total payments',
    unchanged: '8. Terms that remain unchanged',
    action: '9. What you need to do',
    schedule: '10. Revised repayment schedule',
    assumptions: '11. Assumptions used in this illustration',
    contact: '12. Questions and support',
  },
  'fr-CA': {
    purpose: '1. Objet du présent avis',
    amendment: '2. Résumé de la modification',
    postponement: '3. Période de report des remboursements de capital',
    interest: '4. Intérêts pendant le report',
    resumption: '5. Reprise des remboursements de capital',
    maturity: '6. Date d’échéance révisée',
    cost: '7. Incidence sur les intérêts et le total des versements',
    unchanged: '8. Modalités inchangées',
    action: '9. Ce que vous devez faire',
    schedule: '10. Calendrier de remboursement révisé',
    assumptions: '11. Hypothèses utilisées dans cette illustration',
    contact: '12. Questions et soutien',
  },
});

App.i18n.register('chapters', {
  'en-CA': {
    welcome: 'A personal welcome',
    relief: 'Three months of breathing room',
    difference: 'Where the difference comes from',
    tradeoff: 'The trade-off',
    resume: 'Returning to principal payments',
    'next-step': 'Your next step',
  },
  'fr-CA': {
    welcome: 'Un mot de bienvenue',
    relief: 'Trois mois de répit',
    difference: 'D’où vient l’écart',
    tradeoff: 'La contrepartie',
    resume: 'La reprise des remboursements de capital',
    'next-step': 'Votre prochaine étape',
  },
});

App.i18n.register('glossary', {
  'en-CA': {
    title: 'Glossary',
    principal: { term: 'Principal', definition: 'The amount borrowed that remains to be repaid, excluding interest.' },
    interest: { term: 'Interest', definition: 'The cost of borrowing, calculated using the balance and the applicable rate.' },
    postponement: { term: 'Principal postponement', definition: 'Delaying principal payments for a set period. Interest may still be payable during that time.' },
    instalment: { term: 'Instalment', definition: 'A scheduled payment under the financing arrangement.' },
    maturity: { term: 'Maturity date', definition: 'The date the remaining loan balance is scheduled to be fully repaid.' },
    outstanding: { term: 'Outstanding principal', definition: 'Principal still owing at the relevant date.' },
    fixedRate: { term: 'Fixed rate', definition: 'A rate that does not change during the specified fixed-rate period.' },
    cashFlow: { term: 'Cash flow', definition: 'Money coming into and going out of the business.' },
    amortisation: { term: 'Amortisation', definition: 'Repayment of principal over a schedule.' },
    capitalisedInterest: { term: 'Capitalised interest', definition: 'Interest added to the amount owing. This does not occur in this demonstration.' },
  },
  'fr-CA': {
    title: 'Glossaire',
    principal: { term: 'Capital', definition: 'Le montant emprunté qui reste à rembourser, sans les intérêts.' },
    interest: { term: 'Intérêts', definition: 'Le coût de l’emprunt, calculé à partir du solde et du taux applicable.' },
    postponement: { term: 'Report des remboursements de capital', definition: 'Le fait de reporter les remboursements de capital pendant une période déterminée. Des intérêts peuvent rester payables pendant cette période.' },
    instalment: { term: 'Versement', definition: 'Un paiement prévu au calendrier dans le cadre de l’entente de financement.' },
    maturity: { term: 'Date d’échéance', definition: 'La date à laquelle le solde restant du prêt doit être entièrement remboursé.' },
    outstanding: { term: 'Capital restant à rembourser', definition: 'Le capital toujours dû à une date donnée.' },
    fixedRate: { term: 'Taux fixe', definition: 'Un taux qui ne change pas pendant la période à taux fixe indiquée.' },
    cashFlow: { term: 'Trésorerie', definition: 'L’argent qui entre dans l’entreprise et qui en sort.' },
    amortisation: { term: 'Amortissement', definition: 'Le remboursement du capital selon un calendrier.' },
    capitalisedInterest: { term: 'Intérêts capitalisés', definition: 'Des intérêts ajoutés au montant dû. Cela ne se produit pas dans cette démonstration.' },
  },
});
