/* Session insights: approved copy for the presenter view (PRD section 17).
 * Presenter-only page, reached by URL (#/insights) and not linked from the
 * recipient view, so the build's recipient-wording gate exempts it. It keeps
 * its presenter framing: interaction counts from this tab only, never measured
 * BDC outcomes, never an administrative role. Amounts and dates in the evaluation answers are
 * {params} filled from App.record via App.fmt.
 * French drafts are implementation input pending qualified fr-CA review. */
App.i18n.register('insights', {
  'en-CA': {
    overline: 'Presenter view',
    title: 'Session insights',
    intro: 'Interaction events recorded in this browser tab during this session, to help a presenter walk through the notice. Nothing on this page is sent anywhere.',
    actions: {
      label: 'Presenter actions',
      export: 'Export events (JSON)',
      exported: 'Export started: {file}',
    },
    framing: {
      heading: 'How to read this view',
      items: [
        'These are interaction counts from this browser tab only. They are not measured BDC outcomes.',
        'This page needs no sign-in and gives no administrative or secure role.',
        'Completing the video does not show that it was understood.',
        '“Mark as reviewed” is not consent, acceptance or a signature.',
        'Only two request steps exist here: selecting a request button and creating a request (REQ- reference) in this tab. Nothing is sent to BDC, so acceptance by a server and a completed service outcome are never recorded.',
        'Events hold identifiers, language and time only, never question text, names or amounts.',
      ],
    },
    counts: {
      heading: 'Interaction counts',
      total: { one: '{n} event recorded in this tab', other: '{n} events recorded in this tab' },
      groups: {
        navigation: 'Navigation and language',
        understanding: 'Understanding aids',
        actions: 'Actions and feedback',
        other: 'Other events',
      },
    },
    types: {
      notice_opened: { count: 'Notice opened', event: 'Notice opened' },
      section_viewed: { count: 'Sections viewed', event: 'Section viewed' },
      detail_opened: { count: 'Details opened', event: 'Detail opened' },
      glossary_opened: { count: 'Definitions opened', event: 'Definition opened' },
      explain_requested: { count: '“Explain with AI” requests', event: '“Explain with AI” requested' },
      video_started: { count: 'Video starts', event: 'Video started' },
      video_chapter_viewed: { count: 'Video chapters viewed', event: 'Video chapter viewed' },
      video_completed: { count: 'Video completions', event: 'Video completed' },
      query_drafted: { count: 'Questions drafted', event: 'Question drafted' },
      demo_query_created: { count: 'Requests created', event: 'Request created' },
      survey_submitted: { count: 'Survey responses', event: 'Survey response' },
      resource_opened: { count: 'Resources opened', event: 'Resource opened' },
      schedule_exported: { count: 'Schedule exports', event: 'Schedule exported' },
      language_changed: { count: 'Language changes', event: 'Language changed' },
      marked_reviewed: { count: 'Marked as reviewed', event: 'Marked as reviewed' },
    },
    timeline: {
      heading: 'Event timeline',
      intro: 'Newest first. The list updates as you use the notice.',
      showing: 'Showing {n} of {total}',
      empty: 'No events recorded yet.',
      more: 'Show more events',
      id: 'Identifier',
      section: 'Section',
      language: 'Language',
      none: 'None',
      seq: 'Event {n}',
    },
    milestones: {
      heading: 'Milestones',
      reviewed: 'Marked as reviewed',
      reviewedNote: 'A note in this tab only. Not consent or acceptance.',
      survey: 'Clarity survey',
      surveyNone: 'No response',
      surveyNote: 'Stored separately from “Mark as reviewed”. Not a satisfaction or loyalty score.',
      ratings: { unhappy: 'Not clear', neutral: 'Somewhat clear', happy: 'Very clear' },
      requests: 'Requests created',
      requestsNote: 'Created in this tab only. Nothing was sent to or accepted by BDC.',
      draft: 'Question draft in progress',
      yes: 'Yes',
      no: 'No',
    },
    presenter: {
      heading: 'Presenter controls',
      hardship: 'Simulate a hardship/arrears flag (test setting)',
      hardshipDesc: 'When on, “Support for you” hides additional-borrowing suggestions and puts help first. This is a responsible design rule for testing, not a claimed BDC policy. It does not change the notice record.',
      stateOn: 'On: additional-borrowing suggestions are hidden in “Support for you”.',
      stateOff: 'Off: “Support for you” shows its standard suggestions.',
      openSupport: 'Open “Support for you”',
    },
    widget: {
      heading: 'Accessibility widget',
      body: 'The supplied accessibility widget script is requested once when the page loads. It is the only automatic online request, and the notice works without it.',
      present: 'Script element in this page',
      count: 'Script elements found',
      note: 'Present does not mean loaded: the widget can be blocked or unavailable offline.',
      yes: 'Yes',
      no: 'No',
    },
    tasks: {
      heading: 'Usability evaluation tasks',
      intro: 'Ask a participant to complete each task without help, then tick the ones they complete. Ticks stay in this tab only.',
      showAnswer: 'Expected answer',
      goTo: 'Go to {place}',
      done: 'Completed by participant',
      // Accessible names: the visible label first, then the task it belongs to.
      doneLabel: 'Completed by participant: {task}',
      answerLabel: 'Expected answer: {task}',
      progress: { one: '{n} of {total} tasks completed', other: '{n} of {total} tasks completed' },
      pilot: 'A pilot could compare task completion and contact reasons with BDC’s own baseline. This view does not estimate business results.',
      items: {
        nextPayment: {
          task: 'Find the next payment',
          answer: '{amount} on {date}. It covers interest only.',
        },
        resume: {
          task: 'Identify when principal payments resume',
          answer: 'On {date}. That payment is {amount}, principal and interest.',
        },
        owing: {
          task: 'Explain that the principal remains owing',
          answer: 'The {deferred} of postponed principal is still owed. It is repaid later, and the final payment moves to {maturity}.',
        },
        interest: {
          task: 'Identify the additional total interest',
          answer: '{total} more interest over the remaining schedule. The {first} of additional interest during the postponement is part of this {total}, not added to it.',
        },
      },
    },
    languages: { 'en-CA': 'English', 'fr-CA': 'French' },
  },
  'fr-CA': {
    overline: 'Mode présentateur',
    title: 'Statistiques de la séance',
    intro: 'Événements d’interaction enregistrés dans cet onglet pendant la séance, pour aider la personne qui présente à parcourir l’avis. Rien sur cette page n’est transmis.',
    actions: {
      label: 'Actions de présentation',
      export: 'Exporter les événements (JSON)',
      exported: 'Exportation lancée : {file}',
    },
    framing: {
      heading: 'Comment lire cette vue',
      items: [
        'Il s’agit du nombre d’interactions dans cet onglet seulement. Ce ne sont pas des résultats mesurés par BDC.',
        'Cette page ne demande aucune connexion et ne confère aucun rôle administratif ou sécurisé.',
        'Regarder la vidéo jusqu’au bout ne démontre pas qu’elle a été comprise.',
        'La mention « Marquer comme consulté » n’est ni un consentement, ni une acceptation, ni une signature.',
        'Seules deux étapes de demande existent ici : sélectionner un bouton de demande et créer une demande (référence REQ-) dans cet onglet. Rien n’est transmis à BDC; l’acceptation par un serveur et un service rendu ne sont donc jamais enregistrés.',
        'Les événements contiennent uniquement des identifiants, la langue et l’heure, jamais le texte des questions, des noms ou des montants.',
      ],
    },
    counts: {
      heading: 'Nombre d’interactions',
      total: { one: '{n} événement enregistré dans cet onglet', other: '{n} événements enregistrés dans cet onglet' },
      groups: {
        navigation: 'Navigation et langue',
        understanding: 'Aides à la compréhension',
        actions: 'Actions et rétroaction',
        other: 'Autres événements',
      },
    },
    types: {
      notice_opened: { count: 'Avis ouvert', event: 'Avis ouvert' },
      section_viewed: { count: 'Sections consultées', event: 'Section consultée' },
      detail_opened: { count: 'Détails ouverts', event: 'Détail ouvert' },
      glossary_opened: { count: 'Définitions ouvertes', event: 'Définition ouverte' },
      explain_requested: { count: 'Demandes « Expliquer avec l’IA »', event: '« Expliquer avec l’IA » demandé' },
      video_started: { count: 'Lancements de la vidéo', event: 'Vidéo lancée' },
      video_chapter_viewed: { count: 'Chapitres vidéo consultés', event: 'Chapitre vidéo consulté' },
      video_completed: { count: 'Vidéos regardées jusqu’au bout', event: 'Vidéo regardée jusqu’au bout' },
      query_drafted: { count: 'Questions rédigées', event: 'Question rédigée' },
      demo_query_created: { count: 'Demandes créées', event: 'Demande créée' },
      survey_submitted: { count: 'Réponses au sondage', event: 'Réponse au sondage' },
      resource_opened: { count: 'Ressources ouvertes', event: 'Ressource ouverte' },
      schedule_exported: { count: 'Exportations du calendrier', event: 'Calendrier exporté' },
      language_changed: { count: 'Changements de langue', event: 'Langue changée' },
      marked_reviewed: { count: 'Marqué comme consulté', event: 'Marqué comme consulté' },
    },
    timeline: {
      heading: 'Chronologie des événements',
      intro: 'Du plus récent au plus ancien. La liste se met à jour pendant que vous utilisez l’avis.',
      showing: 'Affichage : {n} sur {total}',
      empty: 'Aucun événement enregistré pour l’instant.',
      more: 'Afficher plus d’événements',
      id: 'Identifiant',
      section: 'Section',
      language: 'Langue',
      none: 'Aucune',
      seq: 'Événement {n}',
    },
    milestones: {
      heading: 'Jalons',
      reviewed: 'Marqué comme consulté',
      reviewedNote: 'Une note dans cet onglet seulement. Ni consentement ni acceptation.',
      survey: 'Sondage sur la clarté',
      surveyNone: 'Aucune réponse',
      surveyNote: 'Conservé séparément de « Marquer comme consulté ». Ce n’est pas un indice de satisfaction ou de fidélité.',
      ratings: { unhappy: 'Pas clair', neutral: 'Assez clair', happy: 'Très clair' },
      requests: 'Demandes créées',
      requestsNote: 'Créées dans cet onglet seulement. Rien n’a été transmis à BDC ni accepté par BDC.',
      draft: 'Brouillon de question en cours',
      yes: 'Oui',
      no: 'Non',
    },
    presenter: {
      heading: 'Commandes de présentation',
      hardship: 'Simuler un indicateur de difficultés financières ou d’arriérés (paramètre d’essai)',
      hardshipDesc: 'Lorsque l’option est activée, la section « Du soutien pour vous » masque les suggestions d’emprunt additionnel et met l’aide en priorité. Il s’agit d’une règle de conception responsable pour les essais, et non d’une politique attribuée à BDC. Elle ne modifie pas le dossier de l’avis.',
      stateOn: 'Activée : les suggestions d’emprunt additionnel sont masquées dans la section « Du soutien pour vous ».',
      stateOff: 'Désactivée : la section « Du soutien pour vous » affiche ses suggestions habituelles.',
      openSupport: 'Ouvrir la section « Du soutien pour vous »',
    },
    widget: {
      heading: 'Module d’accessibilité',
      body: 'Le script du module d’accessibilité fourni est demandé une seule fois au chargement de la page. C’est la seule requête en ligne automatique, et l’avis fonctionne sans lui.',
      present: 'Élément de script dans cette page',
      count: 'Éléments de script trouvés',
      note: 'Présent ne veut pas dire chargé : le module peut être bloqué ou indisponible hors ligne.',
      yes: 'Oui',
      no: 'Non',
    },
    tasks: {
      heading: 'Tâches d’évaluation de l’utilisabilité',
      intro: 'Demandez à une personne participante d’accomplir chaque tâche sans aide, puis cochez celles qui sont réussies. Les cases cochées restent dans cet onglet seulement.',
      showAnswer: 'Réponse attendue',
      goTo: 'Ouvrir la section « {place} »',
      done: 'Réussie par la personne participante',
      doneLabel: 'Réussie par la personne participante : {task}',
      answerLabel: 'Réponse attendue : {task}',
      progress: { one: '{n} tâche réussie sur {total}', other: '{n} tâches réussies sur {total}' },
      pilot: 'Un projet pilote pourrait comparer la réussite des tâches et les motifs de communication avec les données de référence de BDC. Cette vue n’estime aucun résultat d’affaires.',
      items: {
        nextPayment: {
          task: 'Trouver le prochain versement',
          answer: '{amount} le {date}. Ce versement couvre uniquement les intérêts.',
        },
        resume: {
          task: 'Repérer la reprise des remboursements de capital',
          answer: 'Le {date}. Ce versement est de {amount}, capital et intérêts compris.',
        },
        owing: {
          task: 'Expliquer que le capital reste dû',
          answer: 'Le capital reporté de {deferred} est toujours dû. Il est remboursé plus tard, et le dernier versement est repoussé au {maturity}.',
        },
        interest: {
          task: 'Repérer le total des intérêts additionnels',
          answer: '{total} d’intérêts de plus sur la durée restante. Les {first} d’intérêts additionnels pendant le report des remboursements de capital font partie de ces {total}; ils ne s’y ajoutent pas.',
        },
      },
    },
    languages: { 'en-CA': 'Anglais', 'fr-CA': 'Français' },
  },
});
