/* Personalised animated explanation (media module): player chrome, scene
 * labels, transcript and end card. Amounts, dates and counts are always
 * passed in as parameters formatted with App.fmt. The narration text itself
 * comes from the embedded cue manifests so it matches the audio exactly.
 * French drafts are implementation input pending qualified fr-CA review. */
App.i18n.register('media', {
  'en-CA': {
    title: 'Your personalised explanation',
    playerLabel: 'Personalised explanation video player',
    roleVideo: 'video',
    forClient: 'For {name} · {company}',
    demoTag: 'Concept demo · Fictional client',
    narratedIn: 'Narrated in English',
    captionsIncluded: 'Captions and transcript',
    stageLabel: '{title}. Chapter {n} of {total}: {chapter}.',
    stageHint: 'Press Space to play or pause. Use the left and right arrow keys to move {n} seconds.',
    play: 'Play',
    pause: 'Pause',
    playExplanation: 'Play your personalised explanation ({duration})',
    replay: 'Replay from the beginning',
    seek: 'Playback position',
    seekValue: '{current} of {total}',
    elapsed: '{current} / {total}',
    chapterLabel: 'Chapter {n} of {total} · {title}',
    chapters: 'Chapters',
    chapterListLabel: 'Video chapters',
    chapterItem: 'Chapter {n}: {title}, starts at {time}',
    current: 'Current',
    speed: 'Playback speed',
    speedValue: '{rate}×',
    captions: 'Captions',
    transcript: 'Transcript',
    mute: 'Mute',
    volume: 'Volume',
    volumeValue: '{n}%',
    fullscreen: 'Full screen',
    exitFullscreen: 'Exit full screen',
    error: 'The narration can’t be played here. The full transcript is below.',
    endedAnnounce: 'The explanation has ended. Your next-step options are shown in the player.',
    missing: 'The explanation can’t be shown in this file. The same information is in “What changed” and “Your notice”.',
    transcriptTitle: 'Transcript',
    transcriptMeta: 'Narration in English · {duration}',
    transcriptIntro: 'The full narration, grouped by chapter. Select a chapter title to play from that point.',
    playFromChapter: 'Play from chapter {n}: {title}',
    note: 'Narration generated before distribution with ElevenLabs text-to-speech and embedded in this file. Playback works offline and never contacts ElevenLabs.',
    voice: 'Voice: {name}, an ElevenLabs premade voice · Model: {model} · Pronunciation pending human review.',
    end: {
      title: 'Your next step',
      text: 'No acceptance is required through this notice.',
      schedule: 'Review the revised schedule',
      clair: 'Ask Clair',
      query: 'Prepare a question',
      replay: 'Watch again',
    },
    s1: {
      overline: 'Your financing update',
      effective: 'Effective {date}',
    },
    s2: {
      title: 'Principal payments postponed',
      period: '{from} to {to}',
      principal: 'Principal',
      interest: 'Interest',
      postponed: 'Postponed',
      interestEach: '{amount} interest each month',
    },
    s3: {
      title: 'Where the difference comes from',
      deferred: 'Principal deferred',
      deferredSub: 'Moved later in the schedule. Still owing.',
      extra: 'Additional interest',
      extraSub: 'During the {n} postponed months',
      relief: 'Lower payments',
      reliefSub: 'Over the {n} postponed months, compared with the original schedule',
      minus: '−',
      equals: '=',
      notForgiveness: 'Temporary cash-flow relief — not debt forgiveness',
    },
    s4: {
      title: 'The trade-off',
      sub: 'Interest continues to accrue',
      original: 'Original final payment',
      revised: 'Revised final payment',
      shift: '{n} months later',
      extraLabel: 'additional interest over the remaining term',
      includes: 'Includes the {amount} of additional interest from the {n} postponed months.',
    },
    s5: {
      title: 'Principal payments resume',
      total: 'Total payment',
      principal: 'principal',
      interest: 'interest',
      equals: '=',
      plus: '+',
      first: 'First payment that includes principal again',
    },
    s6: {
      title: 'Your next step',
      schedule: 'Review the revised schedule',
      explain: 'Explain with AI',
      ask: 'Ask a question',
      noAcceptance: 'No acceptance is required through this notice.',
    },
  },
  'fr-CA': {
    title: 'Votre explication personnalisée',
    playerLabel: 'Lecteur vidéo de l’explication personnalisée',
    roleVideo: 'vidéo',
    forClient: 'Pour {name} · {company}',
    demoTag: 'Démo conceptuelle · Dossier fictif',
    narratedIn: 'Narration en français',
    captionsIncluded: 'Sous-titres et transcription',
    stageLabel: '{title}. Chapitre {n} sur {total}\u00a0: {chapter}.',
    stageHint: 'Appuyez sur la barre d’espacement pour lancer ou interrompre la lecture. Utilisez les flèches gauche et droite pour reculer ou avancer de {n} secondes.',
    play: 'Lecture',
    pause: 'Pause',
    playExplanation: 'Lecture de votre explication personnalisée ({duration})',
    replay: 'Recommencer depuis le début',
    seek: 'Position de lecture',
    seekValue: '{current} sur {total}',
    elapsed: '{current} / {total}',
    chapterLabel: 'Chapitre {n} sur {total} · {title}',
    chapters: 'Chapitres',
    chapterListLabel: 'Chapitres de la vidéo',
    chapterItem: 'Chapitre {n}\u00a0: {title}, commence à {time}',
    current: 'En cours',
    speed: 'Vitesse de lecture',
    speedValue: '{rate}\u00a0×',
    captions: 'Sous-titres',
    transcript: 'Transcription',
    mute: 'Sourdine',
    volume: 'Volume',
    volumeValue: '{n}\u00a0%',
    fullscreen: 'Plein écran',
    exitFullscreen: 'Quitter le plein écran',
    error: 'La narration ne peut pas être lue ici. La transcription complète se trouve ci-dessous.',
    endedAnnounce: 'L’explication est terminée. Les options pour votre prochaine étape s’affichent dans le lecteur.',
    missing: 'L’explication ne peut pas être affichée dans ce fichier. La même information se trouve dans «\u00a0Ce qui change\u00a0» et «\u00a0Votre avis\u00a0».',
    transcriptTitle: 'Transcription',
    transcriptMeta: 'Narration en français · {duration}',
    transcriptIntro: 'La narration complète, regroupée par chapitre. Sélectionnez le titre d’un chapitre pour lancer la lecture à partir de ce point.',
    playFromChapter: 'Lancer la lecture à partir du chapitre {n}\u00a0: {title}',
    note: 'Narration générée avant la distribution au moyen de la synthèse vocale d’ElevenLabs et intégrée à ce fichier. La lecture fonctionne hors ligne et ne communique jamais avec ElevenLabs.',
    voice: 'Voix\u00a0: {name}, une voix prédéfinie d’ElevenLabs · Modèle\u00a0: {model} · Prononciation à faire valider.',
    end: {
      title: 'Votre prochaine étape',
      text: 'Aucune acceptation n’est requise dans cet avis.',
      schedule: 'Consulter le calendrier révisé',
      clair: 'Demander à Clair',
      query: 'Préparer une question',
      replay: 'Revoir la vidéo',
    },
    s1: {
      overline: 'La modification de votre financement',
      effective: 'En vigueur le {date}',
    },
    s2: {
      title: 'Remboursements de capital reportés',
      period: 'De {from} à {to}',
      principal: 'Capital',
      interest: 'Intérêts',
      postponed: 'Reporté',
      interestEach: '{amount} d’intérêts chaque mois',
    },
    s3: {
      title: 'D’où vient l’écart',
      deferred: 'Capital reporté',
      deferredSub: 'Remboursé plus tard dans le calendrier. Toujours dû.',
      extra: 'Intérêts additionnels',
      extraSub: 'Pendant les {n} mois de report',
      relief: 'Baisse des versements',
      reliefSub: 'Sur les {n} mois de report, par rapport au calendrier initial',
      minus: '−',
      equals: '=',
      notForgiveness: 'Allègement temporaire de trésorerie — et non une remise de dette',
    },
    s4: {
      title: 'La contrepartie',
      sub: 'Les intérêts continuent de courir',
      original: 'Dernier versement initial',
      revised: 'Dernier versement révisé',
      shift: '{n} mois plus tard',
      extraLabel: 'd’intérêts additionnels sur la durée restante',
      includes: 'Comprend les {amount} d’intérêts additionnels des {n} mois de report.',
    },
    s5: {
      title: 'Reprise des remboursements de capital',
      total: 'Versement total',
      principal: 'de capital',
      interest: 'd’intérêts',
      equals: '=',
      plus: '+',
      first: 'Premier versement qui comprend de nouveau du capital',
    },
    s6: {
      title: 'Votre prochaine étape',
      schedule: 'Consulter le calendrier révisé',
      explain: 'Expliquer avec l’IA',
      ask: 'Poser une question',
      noAcceptance: 'Aucune acceptation n’est requise dans cet avis.',
    },
  },
});
