/* Your notice (namespace "notice"): formal notice wording, record
 * metadata labels, export and print copy. Amounts, dates and identifiers are
 * always passed in as {params} formatted with App.fmt from the issued record.
 * [[termId|text]] markers become glossary triggers on screen and plain text
 * in print. French drafts are implementation input pending qualified fr-CA
 * review. */
App.i18n.register('notice', {
  'en-CA': {
    overline: 'Formal reference',
    title: 'Your notice',
    intro: 'This is the formal text of your notice. It records the amendment, its effect on your payments and the revised repayment schedule. The other sections explain the same information in plain language.',
    meta: {
      title: 'Record details',
      noticeId: 'Notice identifier',
      recordVersion: 'Record version',
      issueDate: 'Issue date',
      effectiveDate: 'Effective date',
      loanId: 'Loan identifier',
      client: 'Client',
      company: 'Company',
      amendmentStatus: 'Amendment status',
      amendmentStatusValue: 'Approved and completed',
      acceptance: 'Customer acceptance required',
      yes: 'Yes',
      no: 'No',
      fee: 'Change fee',
      processing: 'Payment processing',
      processingValue: 'Not available through this notice',
    },
    actions: {
      title: 'Download and print',
      intro: 'Print a clean copy of this notice, or download the schedules as CSV files for a spreadsheet.',
      print: 'Print / Save as PDF',
      printSub: 'Clean notice layout with the full schedule',
      revisedCsv: 'Download revised schedule (CSV)',
      originalCsv: 'Download original schedule (CSV)',
      paymentsSub: '{count} payments, ISO dates',
      recordJson: 'Download notice record (JSON)',
      recordJsonSub: 'Record data and both schedules',
      pdfNote: 'Browser-generated PDF is a convenience copy, not a certified archival record.',
      downloaded: 'Download started: {file}',
      printOpening: 'Print layout prepared. Your browser’s print dialog is opening.',
    },
    toc: {
      title: 'In this notice',
    },
    letter: {
      aria: 'Formal notice text',
      lhTitle: 'Important financing notice',
      date: 'Date',
      notice: 'Notice',
      loan: 'Loan',
      to: 'To',
      re: 'Re: Loan {loan} — Notice of amendment: principal postponement',
      closingTitle: 'About this document',
      closing: 'This notice is the formal reference for the amendment to loan {loan}. Please keep a copy with your business records.',
    },
    links: {
      plain: 'Read the plain-language explanation',
      plainAria: 'Read the plain-language explanation: {topic}',
      relief: 'See how the lower payments add up',
      reliefAria: 'See how the lower payments add up: {topic}',
      help: 'Go to Help & questions',
      toolsLabel: 'Help with this clause: {topic}',
    },
    text: {
      purpose: {
        p1: 'This notice confirms an amendment to the repayment terms of loan {loan} for {company} and describes its effect on your payments, interest and final payment date.',
        p2: 'It is the formal reference for the plain-language explanations and charts provided with it. Those explanations help you understand this notice; they do not change its terms.',
      },
      amendment: {
        p1Seasonal: 'At the request of the client, {company}, and to support a planned seasonal inventory build, a temporary [[postponement|principal postponement]] on loan {loan} has been approved and completed. The amendment takes effect on {effective}.',
        p1: 'At the request of the client, {company}, a temporary [[postponement|principal postponement]] on loan {loan} has been approved and completed. The amendment takes effect on {effective}.',
        p2: 'The amendment changes when principal is repaid. It does not change the interest rate or reduce the principal owing.',
        summaryLabel: 'Amendment summary',
        type: 'Type of amendment',
        typeValue: 'Principal postponement ({period})',
        status: 'Status',
        effective: 'Effective date',
        fee: 'Change fee',
        acceptance: 'Customer acceptance required through this notice',
      },
      postponement: {
        p1: 'The [[principal|principal]] payments otherwise due in {months} are postponed. For each of these months, the principal payable is {zero}.',
        p2: 'In total, {deferred} of principal is postponed. This principal is not cancelled or reduced: it remains owing and is repaid in later instalments under the revised schedule.',
      },
      interest: {
        p1: '[[interest|Interest]] continues to accrue on the outstanding principal of {opening} at the [[fixedRate|fixed annual rate]] of {rate}, and is payable monthly during the postponement period.',
        p2: 'Each payment due during the postponement period is {interest}, consisting entirely of interest. Because no principal is repaid during this period, the monthly interest does not decrease.',
        p3: 'No interest is [[capitalisedInterest|capitalised]] (added to the principal) as a result of this amendment.',
      },
      resumption: {
        p1: 'Principal payments resume with the payment due on {resume}. From that date, each monthly payment consists of a principal [[instalment|instalment]] of {monthly} plus interest on the outstanding principal.',
        p2: 'The first resumed payment, due on {resume}, is {first}: {monthly} of principal and {firstInterest} of interest. The interest portion then decreases each month as principal is repaid.',
      },
      maturity: {
        p1: 'The final payment date ([[maturity|maturity date]]) changes from {original} to {revised}.',
        p2: 'The revised schedule has {revCount} monthly payments starting {firstDate}, instead of {origCount} under the original schedule.',
      },
      cost: {
        p1: 'Because principal is repaid later, more interest is payable over the remaining schedule. Compared with the original schedule:',
        totalInterest: 'Total interest over the complete remaining schedule increases from {origInt} to {revInt}, an increase of {extra}.',
        totalPayments: 'Total remaining payments increase from {origTotal} to {revTotal}.',
        nearTerm: 'Payments due from {from} to {to} total {revNear} instead of {origNear}, a reduction of {relief}. This equals the {deferred} of postponed principal less {extra3} of additional interest payable during those months.',
        partOf: 'The {extra3} of additional interest payable during those months forms part of the {extra} increase in total interest. It is not charged in addition to it.',
        sameAmount: 'The payments due from {from} to {to} ({revNear}) and the increase in total interest ({extra}) happen to be the same amount. They measure different things.',
        p2: 'The postponed principal of {deferred} remains owing. This amendment does not cancel or reduce any amount owing.',
      },
      unchanged: {
        p1: 'This amendment changes only the timing of principal repayment described above. The following remain unchanged:',
        rate: 'The fixed annual interest rate of {rate}.',
        instalment: 'The monthly principal instalment of {monthly}, once principal payments resume.',
        fee: 'No fee is charged for this amendment (change fee: {fee}).',
        other: 'All other terms and conditions of loan {loan}.',
      },
      action: {
        p1: 'Please review this notice and the revised repayment schedule, and update your internal cash-flow planning to reflect the new payment amounts and dates.',
        p2: 'No acceptance, signature or reply is required through this notice. This document does not process any payment, and no payment can be made through it.',
        p3: 'Your next payment under the revised schedule is {next} on {nextDate}.',
      },
      schedule: {
        p1: 'The revised schedule below lists all {count} remaining monthly payments, from {firstDate} to {lastDate}. It replaces the original schedule from the effective date, {effective}.',
      },
      assumptions: {
        p1: 'The amounts and dates in the schedules of this notice are calculated as follows:',
      },
      contact: {
        p1: 'If you have questions about this notice or your loan, contact your BDC account manager.',
        p2: 'You can also use Help & questions to read answers to common questions, look up terms in the glossary or prepare a question about a specific clause. Clair, your financing guide, can explain any clause in plain language.',
      },
    },
    schedule: {
      first4Title: 'First four payments: original and revised',
      first4Caption: 'First four payments under the original and revised schedules',
      byYearTitle: 'Revised schedule by year',
      expandAll: 'Expand all years',
      collapseAll: 'Collapse all years',
      yearCount: { one: '{n} payment', other: '{n} payments' },
      yearRange: '{from} to {to}',
      yearCaption: 'Revised repayment schedule, {year}',
      cols: {
        no: 'No.',
        date: 'Payment date',
        opening: 'Opening principal',
        principal: 'Principal',
        interest: 'Interest',
        total: 'Total payment',
        totalShort: 'Total',
        closing: 'Closing principal',
      },
      paymentN: 'Payment {n}',
      postponed: 'Principal postponed',
      totalsTitle: 'Schedule totals: original and revised',
      totals: {
        item: 'Item',
        payments: 'Number of payments',
        final: 'Final payment date',
        principal: 'Total principal',
        interest: 'Total interest',
        total: 'Total payments',
      },
      downloadInline: 'Download this schedule (CSV)',
    },
    assumptions: {
      items: [
        'Monthly interest is calculated at the fixed annual rate of {rate} divided by 12, applied to the opening principal for the month and rounded half-up to the nearest cent.',
        'Payments are due on the last calendar day of each month, with no business-day adjustment.',
        'No interest is capitalised (added to the principal).',
        'The schedules include no new advances and no additional or early repayments.',
        'The schedules are shown from {start}; payments and interest before that date are not included.',
      ],
      fallbackNote: 'Shown as written in the notice record (English).',
    },
    csv: {
      noticeId: 'Notice',
      recordVersion: 'Record version',
      status: 'Status',
      loanId: 'Loan',
      company: 'Company',
      schedule: 'Schedule',
      revised: 'Revised repayment schedule',
      original: 'Original repayment schedule',
      issueDate: 'Issue date',
      effectiveDate: 'Effective date',
      currency: 'Currency',
      payments: 'Number of payments',
      source: 'Source',
      sourceValue: 'BDC notice {notice}, record version {version}',
      headers: ['Payment date', 'Payment number', 'Opening principal', 'Principal', 'Interest', 'Total payment', 'Closing principal'],
      totals: 'Totals',
    },
    json: {
      note: 'Notice {notice}, record version {version}: record data with the original and revised repayment schedules. Amounts are in cents; dates are ISO dates.',
    },
    print: {
      title: 'Important financing notice',
      subtitle: 'Notice of amendment: principal postponement',
      scheduleTitle: 'Revised repayment schedule: all {count} payments',
      dateLabel: 'Date:',
      toLabel: 'To:',
      footer: 'Notice {notice} · Record version {version} · {language}',
      language: 'English',
    },
  },
  'fr-CA': {
    overline: 'Référence officielle',
    title: 'Votre avis',
    intro: 'Voici le texte officiel de votre avis. Il consigne la modification, son incidence sur vos versements et le calendrier de remboursement révisé. Les autres sections présentent les mêmes renseignements en langage clair.',
    meta: {
      title: 'Renseignements sur le dossier',
      noticeId: 'Numéro de l’avis',
      recordVersion: 'Version du dossier',
      issueDate: 'Date d’émission',
      effectiveDate: 'Date d’entrée en vigueur',
      loanId: 'Numéro du prêt',
      client: 'Personne cliente',
      company: 'Entreprise',
      amendmentStatus: 'État de la modification',
      amendmentStatusValue: 'Approuvée et effectuée',
      acceptance: 'Acceptation requise de votre part',
      yes: 'Oui',
      no: 'Non',
      fee: 'Frais de modification',
      processing: 'Traitement des paiements',
      processingValue: 'Non offert dans le cadre du présent avis',
    },
    actions: {
      title: 'Télécharger et imprimer',
      intro: 'Imprimez une copie soignée du présent avis ou téléchargez les calendriers en fichiers CSV pour un tableur.',
      print: 'Imprimer / Enregistrer en PDF',
      printSub: 'Mise en page soignée de l’avis, avec le calendrier complet',
      revisedCsv: 'Télécharger le calendrier révisé (CSV)',
      originalCsv: 'Télécharger le calendrier initial (CSV)',
      paymentsSub: '{count} versements, dates ISO',
      recordJson: 'Télécharger le dossier de l’avis (JSON)',
      recordJsonSub: 'Données du dossier et les deux calendriers',
      pdfNote: 'Le PDF généré par le navigateur est une copie pour consultation, et non un document d’archivage certifié.',
      downloaded: 'Téléchargement lancé : {file}',
      printOpening: 'La mise en page d’impression est prête. La fenêtre d’impression de votre navigateur s’ouvre.',
    },
    toc: {
      title: 'Dans cet avis',
    },
    letter: {
      aria: 'Texte officiel de l’avis',
      lhTitle: 'Avis important concernant votre financement',
      date: 'Date',
      notice: 'Avis',
      loan: 'Prêt',
      to: 'Destinataire',
      re: 'Objet : Prêt {loan} — Avis de modification : report des remboursements de capital',
      closingTitle: 'À propos de ce document',
      closing: 'Le présent avis constitue la référence officielle de la modification apportée au prêt {loan}. Veuillez en conserver une copie avec les dossiers de votre entreprise.',
    },
    links: {
      plain: 'Lire l’explication en langage clair',
      plainAria: 'Lire l’explication en langage clair : {topic}',
      relief: 'Voir le calcul des versements réduits',
      reliefAria: 'Voir le calcul des versements réduits : {topic}',
      help: 'Aller à Aide et questions',
      toolsLabel: 'Aide sur cette clause : {topic}',
    },
    text: {
      purpose: {
        p1: 'Le présent avis confirme une modification des modalités de remboursement du prêt {loan} consenti à {company} et décrit son incidence sur vos versements, vos intérêts et la date de votre dernier versement.',
        p2: 'Il constitue la référence officielle des explications en langage clair et des graphiques qui l’accompagnent. Ces explications vous aident à comprendre le présent avis; elles n’en modifient pas les modalités.',
      },
      amendment: {
        p1Seasonal: 'À la demande de l’entreprise cliente, {company}, et afin de soutenir la constitution prévue de stocks saisonniers, un [[postponement|report]] temporaire des remboursements de capital a été approuvé et effectué pour le prêt {loan}. La modification entre en vigueur le {effective}.',
        p1: 'À la demande de l’entreprise cliente, {company}, un [[postponement|report]] temporaire des remboursements de capital a été approuvé et effectué pour le prêt {loan}. La modification entre en vigueur le {effective}.',
        p2: 'La modification porte sur le moment où le capital est remboursé. Elle ne change pas le taux d’intérêt et ne réduit pas le capital dû.',
        summaryLabel: 'Résumé de la modification',
        type: 'Type de modification',
        typeValue: 'Report des remboursements de capital ({period})',
        status: 'État',
        effective: 'Date d’entrée en vigueur',
        fee: 'Frais de modification',
        acceptance: 'Acceptation requise de votre part dans le cadre du présent avis',
      },
      postponement: {
        p1: 'Les remboursements de [[principal|capital]] qui auraient autrement été exigibles en {months} sont reportés. Pour chacun de ces mois, le capital à rembourser est de {zero}.',
        p2: 'Au total, un capital de {deferred} est reporté. Ce capital n’est ni annulé ni réduit : il reste dû et sera remboursé par des versements ultérieurs, selon le calendrier révisé.',
      },
      interest: {
        p1: 'Les [[interest|intérêts]] continuent de courir sur le capital restant dû de {opening}, au [[fixedRate|taux annuel fixe]] de {rate}, et sont payables chaque mois pendant la période de report.',
        p2: 'Chaque versement exigible pendant la période de report s’élève à {interest} et se compose uniquement d’intérêts. Comme aucun capital n’est remboursé pendant cette période, les intérêts mensuels ne diminuent pas.',
        p3: 'Aucun intérêt n’est [[capitalisedInterest|capitalisé]] (ajouté au capital) en raison de cette modification.',
      },
      resumption: {
        p1: 'Les remboursements de capital reprennent avec le versement exigible le {resume}. À compter de cette date, chaque [[instalment|versement]] mensuel comprend un remboursement de capital de {monthly}, plus les intérêts sur le capital restant dû.',
        p2: 'Le premier versement après la reprise, exigible le {resume}, s’élève à {first}, soit {monthly} de capital et {firstInterest} d’intérêts. La part des intérêts diminue ensuite chaque mois, à mesure que le capital est remboursé.',
      },
      maturity: {
        p1: 'La date du dernier versement ([[maturity|date d’échéance]]) passe du {original} au {revised}.',
        p2: 'Le calendrier révisé compte {revCount} versements mensuels à compter du {firstDate}, au lieu de {origCount} selon le calendrier initial.',
      },
      cost: {
        p1: 'Comme le capital est remboursé plus tard, les intérêts payables sur la durée restante du calendrier augmentent. Par rapport au calendrier initial :',
        totalInterest: 'Le total des intérêts sur l’ensemble du calendrier restant passe de {origInt} à {revInt}, soit une hausse de {extra}.',
        totalPayments: 'Le total des versements restants passe de {origTotal} à {revTotal}.',
        nearTerm: 'Les versements exigibles de {from} à {to} totalisent {revNear} au lieu de {origNear}, soit {relief} de moins. Ce montant correspond aux {deferred} de capital reporté, moins {extra3} d’intérêts additionnels payables pendant ces mois.',
        partOf: 'Les {extra3} d’intérêts additionnels payables pendant ces mois font partie de la hausse de {extra} du total des intérêts. Ils ne s’y ajoutent pas.',
        sameAmount: 'Les versements exigibles de {from} à {to} ({revNear}) et la hausse du total des intérêts ({extra}) correspondent par hasard au même montant. Ils mesurent des choses différentes.',
        p2: 'Le capital reporté de {deferred} reste dû. Cette modification n’annule ni ne réduit aucun montant dû.',
      },
      unchanged: {
        p1: 'Cette modification ne change que le moment du remboursement du capital décrit ci-dessus. Les éléments suivants demeurent inchangés :',
        rate: 'Le taux d’intérêt annuel fixe de {rate}.',
        instalment: 'Le versement mensuel de capital de {monthly}, une fois les remboursements de capital repris.',
        fee: 'Aucuns frais ne s’appliquent à cette modification (frais de modification : {fee}).',
        other: 'Toutes les autres modalités et conditions du prêt {loan}.',
      },
      action: {
        p1: 'Veuillez prendre connaissance du présent avis et du calendrier de remboursement révisé, puis mettre à jour la planification de trésorerie de votre entreprise en fonction des nouveaux montants et des nouvelles dates de versement.',
        p2: 'Aucune acceptation, signature ni réponse n’est requise dans le cadre du présent avis. Ce document ne traite aucun paiement et ne permet d’effectuer aucun paiement.',
        p3: 'Votre prochain versement selon le calendrier révisé est de {next}, le {nextDate}.',
      },
      schedule: {
        p1: 'Le calendrier révisé ci-dessous présente les {count} versements mensuels restants, du {firstDate} au {lastDate}. Il remplace le calendrier initial à compter de la date d’entrée en vigueur, le {effective}.',
      },
      assumptions: {
        p1: 'Les montants et les dates des calendriers du présent avis sont établis comme suit :',
      },
      contact: {
        p1: 'Pour toute question sur le présent avis ou sur votre prêt, communiquez avec votre directrice ou directeur de comptes chez BDC.',
        p2: 'Vous pouvez aussi consulter la section Aide et questions pour lire les réponses aux questions fréquentes, chercher un terme dans le glossaire ou préparer une question sur une clause précise. Clair, votre guide du financement, peut vous expliquer n’importe quelle clause en langage clair.',
      },
    },
    schedule: {
      first4Title: 'Quatre premiers versements : initial et révisé',
      first4Caption: 'Quatre premiers versements selon le calendrier initial et le calendrier révisé',
      byYearTitle: 'Calendrier révisé par année',
      expandAll: 'Afficher toutes les années',
      collapseAll: 'Masquer toutes les années',
      yearCount: { one: '{n} versement', other: '{n} versements' },
      yearRange: 'de {from} à {to}',
      yearCaption: 'Calendrier de remboursement révisé, {year}',
      cols: {
        no: 'N°',
        date: 'Date du versement',
        opening: 'Capital au début',
        principal: 'Capital',
        interest: 'Intérêts',
        total: 'Versement total',
        totalShort: 'Total',
        closing: 'Capital à la fin',
      },
      paymentN: 'Versement {n}',
      postponed: 'Capital reporté',
      totalsTitle: 'Totaux des calendriers : initial et révisé',
      totals: {
        item: 'Élément',
        payments: 'Nombre de versements',
        final: 'Date du dernier versement',
        principal: 'Total du capital',
        interest: 'Total des intérêts',
        total: 'Total des versements',
      },
      downloadInline: 'Télécharger ce calendrier (CSV)',
    },
    assumptions: {
      items: [
        'Les intérêts mensuels sont calculés au taux annuel fixe de {rate} divisé par 12, appliqué au capital au début du mois; ils sont arrondis au cent le plus proche (la demie étant arrondie au cent supérieur).',
        'Les versements sont exigibles le dernier jour civil de chaque mois, sans rajustement en fonction des jours ouvrables.',
        'Aucun intérêt n’est capitalisé (ajouté au capital).',
        'Les calendriers ne comprennent aucune nouvelle avance de fonds ni aucun remboursement supplémentaire ou anticipé.',
        'Les calendriers sont présentés à compter du {start}; les versements et les intérêts antérieurs à cette date n’y figurent pas.',
      ],
      fallbackNote: 'Affiché tel qu’il figure dans le dossier de l’avis (en anglais).',
    },
    csv: {
      noticeId: 'Avis',
      recordVersion: 'Version du dossier',
      status: 'État',
      loanId: 'Prêt',
      company: 'Entreprise',
      schedule: 'Calendrier',
      revised: 'Calendrier de remboursement révisé',
      original: 'Calendrier de remboursement initial',
      issueDate: 'Date d’émission',
      effectiveDate: 'Date d’entrée en vigueur',
      currency: 'Devise',
      payments: 'Nombre de versements',
      source: 'Source',
      sourceValue: 'Avis de BDC {notice}, version du dossier {version}',
      headers: ['Date du versement', 'Numéro du versement', 'Capital au début', 'Capital', 'Intérêts', 'Versement total', 'Capital à la fin'],
      totals: 'Totaux',
    },
    json: {
      note: 'Avis {notice}, version du dossier {version} : données du dossier, avec les calendriers de remboursement initial et révisé. Les montants sont exprimés en cents; les dates sont au format ISO.',
    },
    print: {
      title: 'Avis important concernant votre financement',
      subtitle: 'Avis de modification : report des remboursements de capital',
      scheduleTitle: 'Calendrier de remboursement révisé : les {count} versements',
      dateLabel: 'Date :',
      toLabel: 'Destinataire :',
      footer: 'Avis {notice} · Version du dossier {version} · {language}',
      language: 'Français',
    },
  },
});
