/* "Payments & impact" module content (namespace: payments).
 * Every amount, date and count is passed in as a parameter formatted with
 * App.fmt from the issued record; nothing numeric is written here.
 * [[termId|text]] markers become glossary triggers via App.ui.rich().
 * French drafts are implementation input pending qualified fr-CA review. */
App.i18n.register('payments', {
  'en-CA': {
    overline: 'Payments & impact',
    title: 'Your payments, month by month',
    intro: 'Compare the original and revised schedules, see the effect on your cash flow and on your total cost, and download the numbers.',
    summary: 'Your [[principal|principal]] payments for {months} are postponed. During those months you pay only [[interest|interest]], {interest} a month, so your payments are {relief} lower in total. Principal payments resume on {resume}. The revised schedule ends on {revMaturity} and includes {extra} more interest over the remaining term.',
    ofMonth: '{month}',
    ofMonthVowel: '{month}',
    diff: {
      lower: '{amount} lower',
      higher: '{amount} higher',
      same: 'No difference',
      lowerWord: 'lower',
      higherWord: 'higher',
    },
    effect: {
      title: 'Cash flow and total cost',
      intro: 'These are two different measures, so each one has its own card and its own scale.',
    },
    relief: {
      title: '{relief} lower payments from {from} to {to}',
      equation: 'How the {relief} is worked out',
      deferred: 'Principal deferred',
      deferredSub: 'Postponed, not cancelled: it remains owing',
      extra: 'Additional interest within the first three months',
      extraSub: 'Interest on principal that has not been reduced yet',
      result: 'Lower payments',
      resultSub: '{from} to {to}',
      minus: 'minus',
      equals: 'equals',
      paymentsTitle: 'Total payments, {from} to {to}',
      scale: 'Bar lengths use this card’s own scale, from {zero} to {max}.',
      note: 'This is temporary [[cashFlow|cash-flow]] relief. The {deferred} of principal is still owing and is repaid later in the schedule.',
    },
    cost: {
      title: '{extra} more interest over the remaining schedule',
      interestTitle: 'Total interest over the remaining schedule',
      additional: 'Additional interest',
      payments: 'Total remaining payments',
      final: 'Final payment (maturity)',
      scale: 'Bar lengths use this card’s own scale, from {zero} to {max}.',
      note: 'The {extra3} of additional interest within the first three months is already part of the {extra}. It is not added again.',
    },
    chart: {
      title: 'Payments, {from} to {to}',
      intro: 'Each month shows the original payment (hatched grey) beside the revised payment (solid navy). The darker part of each bar is principal; the lighter part is interest.',
      unit: 'Monthly payment (CAD)',
      legendLabel: 'Chart legend',
      legend: {
        origPrincipal: 'Original – principal',
        origInterest: 'Original – interest',
        revPrincipal: 'Revised – principal',
        revInterest: 'Revised – interest',
      },
      postponed: 'Principal postponed',
      groupsLabel: 'Select a month',
      monthAria: '{month}: original payment {original}, revised payment {revised}, {difference}. Show the breakdown.',
      readoutHint: 'Select a month in the chart to see its breakdown.',
      readoutPreview: 'Select to see the full breakdown.',
      seeBreakdown: 'See the full breakdown',
      summaryTitle: 'Summary',
      summary1: 'From {from} to {to}, the revised payment is {revised} a month, interest only, while the original payment ranges from {origHigh} to {origLow}.',
      summary2: 'Principal payments resume on {resume}. That month the revised payment is {first}, which is {diff} more than the original {orig}, because the [[outstanding|outstanding principal]] was not reduced during the postponement.',
      tableCaption: 'Original and revised payments, {from} to {to}',
      month: 'Month',
    },
    balance: {
      title: 'Principal still owing over the remaining term',
      intro: 'The [[amortisation|amortisation]] is the same under both schedules: {monthly} of principal a month. The revised schedule simply starts it later, so the [[outstanding|outstanding principal]] stays higher for longer.',
      unit: 'Principal still owing (CAD)',
      legend: {
        original: 'Original schedule',
        revised: 'Revised schedule',
        band: 'Principal postponement, {from} to {to}',
      },
      labelOriginal: 'Original',
      labelRevised: 'Revised',
      repaid: 'repaid {date}',
      summary: 'Both schedules start with {start} of principal. Under the revised schedule, the outstanding principal stays at {start} until the end of {lastPostponed}, then goes down by {monthly} a month, {period} behind the original. The original schedule is repaid on {origMaturity}; the revised schedule on {revMaturity}.',
      tableCaption: 'Principal still owing at key dates',
      date: 'Date',
      start: '{date} (start of the schedule)',
      originalEnd: '{date} (original final payment)',
      revisedEnd: '{date} (revised final payment)',
      repaidShort: 'Repaid',
    },
    data: {
      show: 'Show the numbers',
      hide: 'Hide the numbers',
    },
    range: {
      legend: 'Months to compare',
      3: 'First three months',
      6: 'First six months',
      all: 'Full remaining term',
    },
    list: {
      title: 'Month by month',
      intro: 'Select a month to compare its opening principal, principal, interest, total payment and closing principal under both schedules.',
      totalsTitle: 'Totals for the months shown: {range}',
      totalsOriginal: 'Original schedule',
      totalsRevised: 'Revised schedule',
      totalsDiff: 'Difference',
      payments: { one: '{n} payment', other: '{n} payments' },
      original: 'Original',
      revised: 'Revised',
      difference: 'Difference',
      paymentOn: 'Payment on {date}',
      noPayment: 'No payment',
      selected: 'Selected',
      showing: 'Showing {range}: {count}.',
      yearOriginal: 'Original {amount}',
      yearRevised: 'Revised {amount}',
      yearOriginalNone: 'Original: no payment',
      yearMonths: { one: '{n} month', other: '{n} months' },
      yearsHint: 'Open a year to see its months.',
      outside: '{month} is selected but is not among the months shown.',
      seeBreakdown: 'See the breakdown',
      tags: {
        postponed: 'Principal postponed',
        resumes: 'Principal resumes',
        finalOriginal: 'Original final payment',
        added: 'Added month',
        finalRevised: 'Revised final payment',
      },
    },
    detail: {
      kicker: 'Selected month',
      title: '{month} payment',
      date: 'Payment date: {date}',
      emptyTitle: 'No month selected',
      emptyText: 'Select a month in the chart or in the list to compare both schedules for that payment.',
      close: 'Close month details',
      announce: 'Showing the {month} payment.',
      compareLabel: 'Breakdown of the {month} payment',
      diff: 'Difference in total payment',
      whyTitle: 'Why it differs',
      why: {
        postponed: 'This month is part of the principal postponement, so no [[principal|principal]] is due. You pay only [[interest|interest]], {interest}, calculated on [[outstanding|outstanding principal]] of {opening}.',
        postponedHigher: 'The interest is {diff} more than under the original schedule because the principal has not been reduced.',
        resumes: 'Principal payments of {principal} resume this month.',
        higherInterest: 'The interest is {diff} more than under the original schedule because the outstanding principal is {revOpening} instead of {origOpening}: the postponed principal is still owing.',
        added: 'The original schedule was fully repaid on {origMaturity}. This payment is part of the {period} added to the end of the revised schedule to repay the postponed principal.',
        finalOriginal: 'This is the last payment of the original schedule. The revised schedule continues until {revMaturity}.',
        finalRevised: 'This is the last payment of the revised schedule. After it, no principal remains owing.',
      },
    },
    csv: {
      noticeId: 'Notice identifier',
      recordVersion: 'Record version',
      loanId: 'Loan identifier',
      status: 'Status',
      statusValue: 'Fictional demonstration – not a BDC offer or agreement',
      currency: 'Currency',
      content: 'Content',
      contentSelection: 'Original and revised payments – {range}',
      contentRevised: 'Full revised schedule',
      contentOriginal: 'Full original schedule',
      generated: 'Generated',
      generatedValue: 'Created locally in this browser from the demonstration record',
      date: 'Payment date',
      number: 'Payment number',
      opening: 'Opening principal',
      principal: 'Principal',
      interest: 'Interest',
      total: 'Total payment',
      closing: 'Closing principal',
      original: 'Original – {column}',
      revised: 'Revised – {column}',
      difference: 'Difference in total payment (revised minus original)',
      totals: 'Total',
    },
    downloads: {
      title: 'Download the schedule',
      intro: 'CSV files are created in this browser from the demonstration record. Amounts are plain numbers in Canadian dollars, ready for a spreadsheet.',
      selection: 'Download displayed selection (CSV)',
      selectionHint: 'Months shown: {range}',
      revised: 'Download full revised schedule (CSV)',
      original: 'Download full original schedule (CSV)',
      started: 'Download started: {file}',
    },
  },
  'fr-CA': {
    overline: 'Versements et incidence',
    title: 'Vos versements, mois par mois',
    intro: 'Comparez le calendrier initial et le calendrier révisé, voyez l’effet sur votre trésorerie et sur le coût total, et téléchargez les chiffres.',
    summary: 'Vos remboursements de [[principal|capital]] de {months} sont reportés. Pendant ces mois, vous payez seulement les [[interest|intérêts]], soit {interest} par mois; vos versements diminuent donc de {relief} au total. Les remboursements de capital reprennent le {resume}. Le calendrier révisé se termine le {revMaturity} et comprend {extra} d’intérêts de plus sur la durée restante.',
    ofMonth: 'de {month}',
    ofMonthVowel: 'd’{month}',
    diff: {
      lower: '{amount} de moins',
      higher: '{amount} de plus',
      same: 'Aucun écart',
      lowerWord: 'de moins',
      higherWord: 'de plus',
    },
    effect: {
      title: 'Trésorerie et coût total',
      intro: 'Il s’agit de deux mesures différentes; chacune a donc sa propre carte et sa propre échelle.',
    },
    relief: {
      title: 'Versements réduits de {relief}, de {from} à {to}',
      equation: 'Comment on arrive à {relief}',
      deferred: 'Capital reporté',
      deferredSub: 'Reporté, et non annulé : ce capital reste dû',
      extra: 'Intérêts additionnels au cours des trois premiers mois',
      extraSub: 'Intérêts sur un capital qui n’a pas encore été réduit',
      result: 'Baisse des versements',
      resultSub: 'de {from} à {to}',
      minus: 'moins',
      equals: 'égale',
      paymentsTitle: 'Total des versements, de {from} à {to}',
      scale: 'La longueur des barres suit l’échelle propre à cette carte, de {zero} à {max}.',
      note: 'Il s’agit d’un allègement temporaire de [[cashFlow|trésorerie]]. Les {deferred} de capital restent dus et sont remboursés plus tard dans le calendrier.',
    },
    cost: {
      title: '{extra} d’intérêts de plus sur la durée restante',
      interestTitle: 'Total des intérêts sur la durée restante',
      additional: 'Intérêts additionnels',
      payments: 'Total des versements restants',
      final: 'Dernier versement (échéance)',
      scale: 'La longueur des barres suit l’échelle propre à cette carte, de {zero} à {max}.',
      note: 'Les {extra3} d’intérêts additionnels des trois premiers mois sont déjà compris dans les {extra}. Ils ne s’y ajoutent pas.',
    },
    chart: {
      title: 'Versements, de {from} à {to}',
      intro: 'Pour chaque mois, le versement initial (gris hachuré) figure à côté du versement révisé (bleu marine plein). La partie foncée de chaque barre correspond au capital; la partie pâle, aux intérêts.',
      unit: 'Versement mensuel ($ CA)',
      legendLabel: 'Légende du graphique',
      legend: {
        origPrincipal: 'Initial – capital',
        origInterest: 'Initial – intérêts',
        revPrincipal: 'Révisé – capital',
        revInterest: 'Révisé – intérêts',
      },
      postponed: 'Capital reporté',
      groupsLabel: 'Choisir un mois',
      monthAria: '{month} : versement initial {original}, versement révisé {revised}, {difference}. Afficher le détail.',
      readoutHint: 'Choisissez un mois dans le graphique pour en voir le détail.',
      readoutPreview: 'Choisissez ce mois pour en voir le détail complet.',
      seeBreakdown: 'Voir le détail complet',
      summaryTitle: 'Résumé',
      summary1: 'De {from} à {to}, le versement révisé est de {revised} par mois, soit uniquement des intérêts, alors que le versement initial varie de {origHigh} à {origLow}.',
      summary2: 'Les remboursements de capital reprennent le {resume}. Ce mois-là, le versement révisé est de {first}, soit {diff} de plus que le versement initial de {orig}, parce que le [[outstanding|capital restant à rembourser]] n’a pas diminué pendant le report.',
      tableCaption: 'Versements initiaux et révisés, de {from} à {to}',
      month: 'Mois',
    },
    balance: {
      title: 'Capital restant à rembourser sur la durée restante',
      intro: 'Le capital est [[amortisation|amorti]] au même rythme dans les deux calendriers, soit {monthly} par mois. Le calendrier révisé commence simplement plus tard; le [[outstanding|capital restant à rembourser]] demeure donc plus élevé plus longtemps.',
      unit: 'Capital restant à rembourser ($ CA)',
      legend: {
        original: 'Calendrier initial',
        revised: 'Calendrier révisé',
        band: 'Report des remboursements de capital, de {from} à {to}',
      },
      labelOriginal: 'Initial',
      labelRevised: 'Révisé',
      repaid: 'remboursé en {date}',
      summary: 'Les deux calendriers commencent avec un capital de {start}. Selon le calendrier révisé, le capital restant à rembourser demeure à {start} jusqu’à la fin de {lastPostponed}, puis diminue de {monthly} par mois, avec {period} de décalage par rapport au calendrier initial. Le calendrier initial est remboursé le {origMaturity}; le calendrier révisé, le {revMaturity}.',
      tableCaption: 'Capital restant à rembourser à des dates clés',
      date: 'Date',
      start: '{date} (début du calendrier)',
      originalEnd: '{date} (dernier versement initial)',
      revisedEnd: '{date} (dernier versement révisé)',
      repaidShort: 'Remboursé',
    },
    data: {
      show: 'Afficher les chiffres',
      hide: 'Masquer les chiffres',
    },
    range: {
      legend: 'Mois à comparer',
      3: 'Trois premiers mois',
      6: 'Six premiers mois',
      all: 'Durée restante complète',
    },
    list: {
      title: 'Mois par mois',
      intro: 'Choisissez un mois pour comparer le capital au début, le capital, les intérêts, le versement total et le capital à la fin selon les deux calendriers.',
      totalsTitle: 'Totaux des mois affichés : {range}',
      totalsOriginal: 'Calendrier initial',
      totalsRevised: 'Calendrier révisé',
      totalsDiff: 'Écart',
      payments: { one: '{n} versement', other: '{n} versements' },
      original: 'Initial',
      revised: 'Révisé',
      difference: 'Écart',
      paymentOn: 'Versement du {date}',
      noPayment: 'Aucun versement',
      selected: 'Sélectionné',
      showing: 'Affichage : {range}, {count}.',
      yearOriginal: 'Initial {amount}',
      yearRevised: 'Révisé {amount}',
      yearOriginalNone: 'Initial : aucun versement',
      yearMonths: { one: '{n} mois', other: '{n} mois' },
      yearsHint: 'Ouvrez une année pour en voir les mois.',
      outside: '{month} est sélectionné, mais ne fait pas partie des mois affichés.',
      seeBreakdown: 'Voir le détail',
      tags: {
        postponed: 'Capital reporté',
        resumes: 'Reprise du capital',
        finalOriginal: 'Dernier versement initial',
        added: 'Mois ajouté',
        finalRevised: 'Dernier versement révisé',
      },
    },
    detail: {
      kicker: 'Mois sélectionné',
      title: 'Versement {month}',
      date: 'Date du versement : {date}',
      emptyTitle: 'Aucun mois sélectionné',
      emptyText: 'Choisissez un mois dans le graphique ou dans la liste pour comparer les deux calendriers pour ce versement.',
      close: 'Fermer le détail du mois',
      announce: 'Affichage du versement {month}.',
      compareLabel: 'Détail du versement {month}',
      diff: 'Écart du versement total',
      whyTitle: 'Pourquoi le montant diffère',
      why: {
        postponed: 'Ce mois fait partie du report des remboursements de capital : aucun remboursement de [[principal|capital]] n’est exigible. Vous payez seulement les [[interest|intérêts]], soit {interest}, calculés sur un [[outstanding|capital restant à rembourser]] de {opening}.',
        postponedHigher: 'Les intérêts sont supérieurs de {diff} à ceux du calendrier initial, parce que le capital n’a pas été réduit.',
        resumes: 'Les remboursements de capital de {principal} reprennent ce mois-ci.',
        higherInterest: 'Les intérêts sont supérieurs de {diff} à ceux du calendrier initial, parce que le capital restant à rembourser est de {revOpening} au lieu de {origOpening} : le capital reporté est toujours dû.',
        added: 'Le calendrier initial était entièrement remboursé le {origMaturity}. Ce versement fait partie des {period} ajoutés à la fin du calendrier révisé pour rembourser le capital reporté.',
        finalOriginal: 'Il s’agit du dernier versement du calendrier initial. Le calendrier révisé se poursuit jusqu’au {revMaturity}.',
        finalRevised: 'Il s’agit du dernier versement du calendrier révisé. Après ce versement, il ne reste aucun capital à rembourser.',
      },
    },
    csv: {
      noticeId: 'Numéro de l’avis',
      recordVersion: 'Version du dossier',
      loanId: 'Numéro du prêt',
      status: 'Statut',
      statusValue: 'Démonstration fictive – ni une offre ni une entente de BDC',
      currency: 'Devise',
      content: 'Contenu',
      contentSelection: 'Versements initiaux et révisés – {range}',
      contentRevised: 'Calendrier révisé complet',
      contentOriginal: 'Calendrier initial complet',
      generated: 'Création',
      generatedValue: 'Fichier créé localement dans ce navigateur à partir du dossier de démonstration',
      date: 'Date du versement',
      number: 'Numéro du versement',
      opening: 'Capital au début',
      principal: 'Capital',
      interest: 'Intérêts',
      total: 'Versement total',
      closing: 'Capital à la fin',
      original: 'Initial – {column}',
      revised: 'Révisé – {column}',
      difference: 'Écart du versement total (révisé moins initial)',
      totals: 'Total',
    },
    downloads: {
      title: 'Télécharger le calendrier',
      intro: 'Les fichiers CSV sont créés dans ce navigateur à partir du dossier de démonstration. Les montants sont des nombres simples en dollars canadiens, prêts pour un tableur.',
      selection: 'Télécharger la sélection affichée (CSV)',
      selectionHint: 'Mois affichés : {range}',
      revised: 'Télécharger le calendrier révisé complet (CSV)',
      original: 'Télécharger le calendrier initial complet (CSV)',
      started: 'Téléchargement lancé : {file}',
    },
  },
});
