/* Query form: approved copy for the local demo request (PRD section 10, AC-15, AC-23).
 * The form is separate from Clair. It never sends anything, never collects
 * contact details and never stores the question outside this browser tab.
 * French drafts are implementation input pending qualified fr-CA review. */
App.i18n.register('query', {
  'en-CA': {
    title: 'Ask a question',
    subtitle: 'Local demo only. Nothing is sent to BDC.',
    stepCount: 'Step {n} of {total}',
    stepSep: ': ',
    steps: {
      draft: 'Write your question',
      review: 'Review your request',
      confirm: 'Demo request created',
    },
    intro: 'Prepare a question about this notice. You will check it before a demo request is created in this browser tab.',
    context: {
      heading: 'Included with your question',
      hint: 'The notice identifier is always included. You can remove the selected item.',
      notice: 'Notice',
      always: 'Always included',
      item: 'Selected item',
      none: 'None (general question about this notice)',
      remove: 'Remove',
      removeLabel: 'Remove selected item: {item}',
      restore: 'Add it back',
      restoreLabel: 'Add it back: {item}',
      removed: 'The selected item was removed from your request.',
      restored: 'The selected item was added back to your request.',
      language: 'Preferred language',
      languageHint: 'Your current display language',
    },
    topic: {
      label: 'Topic',
      placeholder: 'Choose a topic',
      options: {
        payment: 'Payment amount',
        interest: 'Interest',
        maturity: 'Maturity',
        understanding: 'Understanding the change',
        other: 'Other',
      },
    },
    question: {
      label: 'Your question',
      hint: 'Use your own words. Up to {max} characters.',
      writtenIn: 'Written in {language}',
      keptAsWritten: 'Your question stays in the language you wrote it in. It is never translated.',
    },
    counter: {
      empty: 'You can enter up to {max} characters',
      remaining: { one: 'You have {n} character remaining', other: 'You have {n} characters remaining' },
      over: { one: 'You have {n} character too many', other: 'You have {n} characters too many' },
    },
    contact: {
      legend: 'Preferred contact method (optional)',
      hint: 'No contact details are collected in this demo.',
      options: {
        none: 'No preference',
        phone: 'Phone call',
        email: 'Email',
        secure: 'Secure message',
      },
    },
    privacy: {
      title: 'Keep it private',
      body: 'Do not include passwords, bank-account details, government identifiers or real contact information. This demo keeps your question in this browser tab only and sends nothing.',
    },
    draftKept: 'If you close this panel, your draft is kept in this tab until you reset the demo.',
    continue: 'Continue to review',
    errors: {
      title: 'There is a problem',
      prefix: 'Error:',
      topic: 'Choose a topic for your question',
      questionEmpty: 'Enter your question',
      questionTooLong: 'Your question must be {max} characters or fewer',
    },
    review: {
      intro: 'Check the details below. Nothing is created until you select “Create demo request”.',
      notice: 'Notice',
      item: 'Selected item',
      none: 'None',
      topic: 'Topic',
      language: 'Preferred language',
      questionLanguage: 'Language of your question',
      contact: 'Preferred contact method',
      question: 'Your question',
      edit: 'Edit',
      create: 'Create demo request',
      note: 'The demo request stays in this browser tab. It is not sent to BDC and does not start a service request.',
    },
    confirm: {
      heading: 'Kept in this browser tab only',
      text: 'Demo request created locally. Nothing has been sent to BDC.',
      refLabel: 'Demo reference',
      notCase: 'This reference exists only in this demonstration. It is not a case number or an acknowledgement from BDC, and no one will contact you. A real service would confirm receipt separately.',
      summaryHeading: 'Plain-text summary',
      summaryLabel: 'Summary of demo request {ref}',
      copy: 'Copy summary',
      copied: 'Summary copied to the clipboard.',
      copyFailed: 'Copying is not available in this browser. Select the summary text and copy it manually.',
      downloadsHeading: 'Optional downloads',
      downloadJson: 'Download JSON',
      downloadTxt: 'Download text (.txt)',
      downloaded: 'Download started: {file}',
      newQuestion: 'Start a new question',
      close: 'Close',
    },
    summary: {
      title: 'Demo request {ref}',
      line: '{label}: {value}',
      created: 'Created',
      questionHeading: 'Question (kept in the language it was written in):',
      disclaimer: 'Local demonstration record only. It is not a case acknowledgement from BDC.',
    },
    languages: { 'en-CA': 'English', 'fr-CA': 'French' },
    languageValues: { 'en-CA': 'English', 'fr-CA': 'French' },
    announce: {
      errors: { one: 'There is {n} problem with your request.', other: 'There are {n} problems with your request.' },
    },
  },
  'fr-CA': {
    title: 'Poser une question',
    subtitle: 'Démo locale seulement. Rien n’est envoyé à BDC.',
    stepCount: 'Étape {n} sur {total}',
    stepSep: ' : ',
    steps: {
      draft: 'Rédigez votre question',
      review: 'Vérifiez votre demande',
      confirm: 'Demande de démonstration créée',
    },
    intro: 'Préparez une question au sujet de cet avis. Vous pourrez la vérifier avant qu’une demande de démonstration soit créée dans cet onglet.',
    context: {
      heading: 'Renseignements joints à votre question',
      hint: 'Le numéro de l’avis est toujours inclus. Vous pouvez retirer l’élément sélectionné.',
      notice: 'Avis',
      always: 'Toujours inclus',
      item: 'Élément sélectionné',
      none: 'Aucun (question générale sur cet avis)',
      remove: 'Retirer',
      removeLabel: 'Retirer l’élément sélectionné : {item}',
      restore: 'Rétablir',
      restoreLabel: 'Rétablir l’élément sélectionné : {item}',
      removed: 'L’élément sélectionné a été retiré de votre demande.',
      restored: 'L’élément sélectionné a été rétabli dans votre demande.',
      language: 'Langue préférée',
      languageHint: 'Votre langue d’affichage actuelle',
    },
    topic: {
      label: 'Sujet',
      placeholder: 'Choisissez un sujet',
      options: {
        payment: 'Montant du versement',
        interest: 'Intérêts',
        maturity: 'Échéance',
        understanding: 'Comprendre la modification',
        other: 'Autre',
      },
    },
    question: {
      label: 'Votre question',
      hint: 'Utilisez vos propres mots. Jusqu’à {max} caractères.',
      writtenIn: 'Rédigée en {language}',
      keptAsWritten: 'Votre question reste dans la langue dans laquelle vous l’avez rédigée. Elle n’est jamais traduite.',
    },
    counter: {
      empty: 'Vous pouvez saisir jusqu’à {max} caractères',
      remaining: { one: 'Il vous reste {n} caractère', other: 'Il vous reste {n} caractères' },
      over: { one: 'Vous avez {n} caractère de trop', other: 'Vous avez {n} caractères de trop' },
    },
    contact: {
      legend: 'Mode de communication préféré (facultatif)',
      hint: 'Aucune coordonnée n’est recueillie dans cette démo.',
      options: {
        none: 'Aucune préférence',
        phone: 'Appel téléphonique',
        email: 'Courriel',
        secure: 'Message sécurisé',
      },
    },
    privacy: {
      title: 'Protégez vos renseignements',
      body: 'N’indiquez aucun mot de passe, renseignement bancaire, numéro d’identification gouvernemental ni coordonnée réelle. Cette démo conserve votre question dans cet onglet seulement et n’envoie rien.',
    },
    draftKept: 'Si vous fermez ce panneau, votre brouillon reste dans cet onglet jusqu’à la réinitialisation de la démo.',
    continue: 'Vérifier ma demande',
    errors: {
      title: 'Veuillez corriger ce qui suit',
      prefix: 'Erreur :',
      topic: 'Choisissez un sujet pour votre question',
      questionEmpty: 'Saisissez votre question',
      questionTooLong: 'Votre question doit compter au plus {max} caractères',
    },
    review: {
      intro: 'Vérifiez les renseignements ci-dessous. Rien n’est créé tant que vous n’avez pas sélectionné « Créer la demande de démonstration ».',
      notice: 'Avis',
      item: 'Élément sélectionné',
      none: 'Aucun',
      topic: 'Sujet',
      language: 'Langue préférée',
      questionLanguage: 'Langue de votre question',
      contact: 'Mode de communication préféré',
      question: 'Votre question',
      edit: 'Modifier',
      create: 'Créer la demande de démonstration',
      note: 'La demande de démonstration reste dans cet onglet. Elle n’est pas envoyée à BDC et ne crée aucune demande de service.',
    },
    confirm: {
      heading: 'Conservée dans cet onglet seulement',
      text: 'Demande de démonstration créée localement. Rien n’a été envoyé à BDC.',
      refLabel: 'Référence de démonstration',
      notCase: 'Cette référence existe uniquement dans cette démonstration. Il ne s’agit ni d’un numéro de dossier ni d’un accusé de réception de BDC, et personne ne communiquera avec vous. Un service réel confirmerait la réception séparément.',
      summaryHeading: 'Résumé en texte brut',
      summaryLabel: 'Résumé de la demande de démonstration {ref}',
      copy: 'Copier le résumé',
      copied: 'Résumé copié dans le presse-papiers.',
      copyFailed: 'La copie n’est pas possible dans ce navigateur. Sélectionnez le texte du résumé et copiez-le manuellement.',
      downloadsHeading: 'Téléchargements facultatifs',
      downloadJson: 'Télécharger en JSON',
      downloadTxt: 'Télécharger en texte (.txt)',
      downloaded: 'Téléchargement lancé : {file}',
      newQuestion: 'Poser une autre question',
      close: 'Fermer',
    },
    summary: {
      title: 'Demande de démonstration {ref}',
      line: '{label} : {value}',
      created: 'Date de création',
      questionHeading: 'Question (conservée dans la langue de rédaction) :',
      disclaimer: 'Document de démonstration local seulement. Il ne s’agit pas d’un accusé de réception de BDC.',
    },
    languages: { 'en-CA': 'anglais', 'fr-CA': 'français' },
    languageValues: { 'en-CA': 'Anglais', 'fr-CA': 'Français' },
    announce: {
      errors: { one: 'Votre demande comporte {n} problème.', other: 'Votre demande comporte {n} problèmes.' },
    },
  },
});
