/* Query form: approved copy for "Ask a question" (PRD section 10, AC-15, AC-23).
 * Recipient view: the copy reads as the recipient sees it, without framing words,
 * and never claims the question was sent to, received by or will be answered by
 * BDC. The form never collects contact details and keeps the question in memory
 * for this tab only. French drafts are implementation input pending qualified
 * fr-CA review. */
App.i18n.register('query', {
  'en-CA': {
    title: 'Ask a question',
    subtitle: 'Your question will include the details of this notice.',
    stepCount: 'Step {n} of {total}',
    stepSep: ': ',
    steps: {
      draft: 'Write your question',
      review: 'Review your request',
      confirm: 'Request created',
    },
    intro: 'Prepare a question about this notice. You can review it before you create your request.',
    context: {
      heading: 'Included with your question',
      hint: 'The notice identifier is always included. You can remove the selected item.',
      notice: 'Notice',
      always: 'Always included',
      item: 'Selected item',
      none: 'None (general question about this notice)',
      remove: 'Remove',
      removeLabel: 'Remove selected item: {item}',
      restore: 'Add it back',
      restoreLabel: 'Add it back: {item}',
      removed: 'The selected item was removed from your request.',
      restored: 'The selected item was added back to your request.',
      language: 'Preferred language',
      languageHint: 'Your current display language',
    },
    topic: {
      label: 'Topic',
      placeholder: 'Choose a topic',
      options: {
        payment: 'Payment amount',
        interest: 'Interest',
        maturity: 'Maturity',
        understanding: 'Understanding the change',
        other: 'Other',
      },
    },
    question: {
      label: 'Your question',
      hint: 'Use your own words. Up to {max} characters.',
      writtenIn: 'Written in {language}',
      keptAsWritten: 'Your question stays in the language you wrote it in. It is never translated.',
    },
    counter: {
      empty: 'You can enter up to {max} characters',
      remaining: { one: 'You have {n} character remaining', other: 'You have {n} characters remaining' },
      over: { one: 'You have {n} character too many', other: 'You have {n} characters too many' },
    },
    contact: {
      legend: 'Preferred contact method (optional)',
      hint: 'Your preference is saved with your question.',
      options: {
        none: 'No preference',
        phone: 'Phone call',
        email: 'Email',
        secure: 'Secure message',
      },
    },
    privacy: {
      title: 'Keep it private',
      body: 'Do not include passwords, banking details or government identifiers in your question.',
    },
    draftKept: 'If you close this panel, your draft is kept in this tab until you clear your activity.',
    continue: 'Continue to review',
    errors: {
      title: 'There is a problem',
      prefix: 'Error:',
      topic: 'Choose a topic for your question',
      questionEmpty: 'Enter your question',
      questionTooLong: 'Your question must be {max} characters or fewer',
    },
    review: {
      intro: 'Check the details below. Nothing is created until you select “Create request”.',
      notice: 'Notice',
      item: 'Selected item',
      none: 'None',
      topic: 'Topic',
      language: 'Preferred language',
      questionLanguage: 'Language of your question',
      contact: 'Preferred contact method',
      question: 'Your question',
      edit: 'Edit',
      create: 'Create request',
      note: 'Creating the request gives you a reference and a summary you can copy or download.',
    },
    confirm: {
      text: 'Your question has been recorded with reference {ref}. Keep this reference for your records.',
      refLabel: 'Reference',
      next: 'To discuss your question, contact your BDC account manager. You can copy or download the summary below.',
      summaryHeading: 'Plain-text summary',
      summaryLabel: 'Summary of request {ref}',
      copy: 'Copy summary',
      copied: 'Summary copied to the clipboard.',
      copyFailed: 'Copying is not available in this browser. Select the summary text and copy it manually.',
      downloadsHeading: 'Optional downloads',
      downloadJson: 'Download JSON',
      downloadTxt: 'Download text (.txt)',
      downloaded: 'Download started: {file}',
      newQuestion: 'Start a new question',
      close: 'Close',
    },
    summary: {
      title: 'Request {ref}',
      line: '{label}: {value}',
      created: 'Created',
      questionHeading: 'Question (kept in the language it was written in):',
      contact: 'To discuss your question, contact your BDC account manager.',
    },
    languages: { 'en-CA': 'English', 'fr-CA': 'French' },
    languageValues: { 'en-CA': 'English', 'fr-CA': 'French' },
    announce: {
      errors: { one: 'There is {n} problem with your request.', other: 'There are {n} problems with your request.' },
    },
  },
  'fr-CA': {
    title: 'Poser une question',
    subtitle: 'Votre question comprendra les renseignements de cet avis.',
    stepCount: 'Étape {n} sur {total}',
    stepSep: ' : ',
    steps: {
      draft: 'Rédigez votre question',
      review: 'Vérifiez votre demande',
      confirm: 'Demande créée',
    },
    intro: 'Préparez une question au sujet de cet avis. Vous pourrez la vérifier avant de créer votre demande.',
    context: {
      heading: 'Renseignements joints à votre question',
      hint: 'Le numéro de l’avis est toujours inclus. Vous pouvez retirer l’élément sélectionné.',
      notice: 'Avis',
      always: 'Toujours inclus',
      item: 'Élément sélectionné',
      none: 'Aucun (question générale sur cet avis)',
      remove: 'Retirer',
      removeLabel: 'Retirer l’élément sélectionné : {item}',
      restore: 'Rétablir',
      restoreLabel: 'Rétablir l’élément sélectionné : {item}',
      removed: 'L’élément sélectionné a été retiré de votre demande.',
      restored: 'L’élément sélectionné a été rétabli dans votre demande.',
      language: 'Langue préférée',
      languageHint: 'Votre langue d’affichage actuelle',
    },
    topic: {
      label: 'Sujet',
      placeholder: 'Choisissez un sujet',
      options: {
        payment: 'Montant du versement',
        interest: 'Intérêts',
        maturity: 'Échéance',
        understanding: 'Comprendre la modification',
        other: 'Autre',
      },
    },
    question: {
      label: 'Votre question',
      hint: 'Utilisez vos propres mots. Jusqu’à {max} caractères.',
      writtenIn: 'Rédigée en {language}',
      keptAsWritten: 'Votre question reste dans la langue dans laquelle vous l’avez rédigée. Elle n’est jamais traduite.',
    },
    counter: {
      empty: 'Vous pouvez saisir jusqu’à {max} caractères',
      remaining: { one: 'Il vous reste {n} caractère', other: 'Il vous reste {n} caractères' },
      over: { one: 'Vous avez {n} caractère de trop', other: 'Vous avez {n} caractères de trop' },
    },
    contact: {
      legend: 'Mode de communication préféré (facultatif)',
      hint: 'Votre préférence est enregistrée avec votre question.',
      options: {
        none: 'Aucune préférence',
        phone: 'Appel téléphonique',
        email: 'Courriel',
        secure: 'Message sécurisé',
      },
    },
    privacy: {
      title: 'Protégez vos renseignements',
      body: 'N’indiquez aucun mot de passe, renseignement bancaire ni numéro d’identification gouvernemental dans votre question.',
    },
    draftKept: 'Si vous fermez ce panneau, votre brouillon reste dans cet onglet jusqu’à ce que vous effaciez votre activité.',
    continue: 'Vérifier ma demande',
    errors: {
      title: 'Veuillez corriger ce qui suit',
      prefix: 'Erreur :',
      topic: 'Choisissez un sujet pour votre question',
      questionEmpty: 'Saisissez votre question',
      questionTooLong: 'Votre question doit compter au plus {max} caractères',
    },
    review: {
      intro: 'Vérifiez les renseignements ci-dessous. Rien n’est créé tant que vous n’avez pas sélectionné « Créer la demande ».',
      notice: 'Avis',
      item: 'Élément sélectionné',
      none: 'Aucun',
      topic: 'Sujet',
      language: 'Langue préférée',
      questionLanguage: 'Langue de votre question',
      contact: 'Mode de communication préféré',
      question: 'Votre question',
      edit: 'Modifier',
      create: 'Créer la demande',
      note: 'Une fois la demande créée, vous obtiendrez une référence et un résumé à copier ou à télécharger.',
    },
    confirm: {
      text: 'Votre question a été enregistrée sous la référence {ref}. Conservez cette référence pour vos dossiers.',
      refLabel: 'Référence',
      next: 'Pour discuter de votre question, communiquez avec votre directrice ou directeur de comptes chez BDC. Vous pouvez copier ou télécharger le résumé ci-dessous.',
      summaryHeading: 'Résumé en texte brut',
      summaryLabel: 'Résumé de la demande {ref}',
      copy: 'Copier le résumé',
      copied: 'Résumé copié dans le presse-papiers.',
      copyFailed: 'La copie n’est pas possible dans ce navigateur. Sélectionnez le texte du résumé et copiez-le manuellement.',
      downloadsHeading: 'Téléchargements facultatifs',
      downloadJson: 'Télécharger en JSON',
      downloadTxt: 'Télécharger en texte (.txt)',
      downloaded: 'Téléchargement lancé : {file}',
      newQuestion: 'Poser une autre question',
      close: 'Fermer',
    },
    summary: {
      title: 'Demande {ref}',
      line: '{label} : {value}',
      created: 'Date de création',
      questionHeading: 'Question (conservée dans la langue de rédaction) :',
      contact: 'Pour discuter de votre question, communiquez avec votre directrice ou directeur de comptes chez BDC.',
    },
    languages: { 'en-CA': 'anglais', 'fr-CA': 'français' },
    languageValues: { 'en-CA': 'Anglais', 'fr-CA': 'Français' },
    announce: {
      errors: { one: 'Votre demande comporte {n} problème.', other: 'Votre demande comporte {n} problèmes.' },
    },
  },
});
